### ISSUE TITLE
Introduce macros to check API versions in XS

### ISSUE THREAD

**Issue by atoomic** [atoomic/perl#1]
provide some easy macro for avoiding the ugliness from
https://github.com/atoomic/perl/commit/6e4e41cfacbfd7eaa64bac9271dd48adac8418f8

**Comment by atoomic** [comment]
```c
vutil.c:620:#if PERL_VERSION_GE(5,19,0)

 #define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
 #define PERL_DECIMAL_VERSION \
     PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
 #define PERL_VERSION_LT(r,v,s) \
     (PERL_DECIMAL_VERSION < PERL_VERSION_DECIMAL(r,v,s))
 #define PERL_VERSION_GE(r,v,s) \
     (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
```

**Comment by atoomic** [comment]
used in 65ce00caa5ead071490555ba42d94556030db610 
but we probably want to extract the helpers to Devel::PPPort and another .h file?

**Comment by khwilliamson** [comment]
Isn't this closable?

**Comment by atoomic** [comment]
yes we can close this as the work is done, not in blead but in alpha
