### ISSUE TITLE
How should we work on files underneath cpan/?

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#117]
Main question, and then a sub-question.

Since modules under `cpan/` are maintained upstream on CPAN and then only subsequently synched into the core distribution, changes in such modules and test files to make them compatible with Perl 7 semantics must (unless we evolve a new protocol) first be submitted to upstream bug trackers.  We should, however, allow other contributors access to our branches to that they can "practice" creating bug reports that (ideally) will allow a module or test to run on either 5 or 7 without modification.

There are 74 subdirectories underneath `cpan/` in the core distribution.
```
$ ls cpan | wc -l
74
```
If we took the approach we did earlier this month, that would suggest creating 74 tickets, one for each directory, and posting a chunk of `make test_harness` results to each.  We could then instruct newcomers to p7 research on how to work simultaneously on the versions here and the versions on CPAN which are presumably passing on Perl 5.

And now, the subquestion.

Of the files under `cpan/`, 108 of them have the string `use p5` in them.
```
$ ack -l '^use [pv]5;' cpan/ |sort
cpan/bignum/lib/bigint.pm
cpan/CPAN/lib/CPAN/Author.pm
cpan/CPAN/lib/CPAN/Bundle.pm
cpan/CPAN/lib/CPAN/Complete.pm
cpan/CPAN/lib/CPAN/Distribution.pm
cpan/CPAN/lib/CPAN/Distroprefs.pm
cpan/CPAN/lib/CPAN/FirstTime.pm
cpan/CPAN/lib/CPAN/HandleConfig.pm
cpan/CPAN/lib/CPAN/Index.pm
cpan/CPAN/lib/CPAN/InfoObj.pm
cpan/CPAN/lib/CPAN/Module.pm
cpan/CPAN/lib/CPAN/Nox.pm
cpan/CPAN/lib/CPAN/Plugin/Specfile.pm
cpan/CPAN/lib/CPAN.pm
cpan/CPAN/lib/CPAN/Prompt.pm
cpan/CPAN/lib/CPAN/Shell.pm
cpan/CPAN/lib/CPAN/Tarzip.pm
cpan/CPAN-Meta-Requirements/t/bad_version_hook.t
cpan/CPAN-Meta-Requirements/t/basic.t
cpan/CPAN-Meta-Requirements/t/finalize.t
cpan/CPAN-Meta-Requirements/t/from-hash.t
cpan/CPAN-Meta-Requirements/t/merge.t
cpan/CPAN-Meta-Requirements/t/strings.t
cpan/CPAN-Meta/t/prereqs-finalize.t
cpan/Digest-MD5/MD5.pm
cpan/Encode/Encode.pm
cpan/Encode/lib/Encode/Alias.pm
cpan/Encode/lib/Encode/CN/HZ.pm
cpan/Encode/lib/Encode/GSM0338.pm
cpan/Encode/lib/Encode/Guess.pm
cpan/Encode/lib/Encode/JP/JIS7.pm
cpan/Encode/lib/Encode/MIME/Header.pm
cpan/Encode/lib/Encode/Unicode/UTF7.pm
cpan/Encode/t/decode.t
cpan/ExtUtils-Constant/lib/ExtUtils/Constant.pm
cpan/ExtUtils-Install/lib/ExtUtils/Install.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/Command/MM.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/MakeMaker.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/MakeMaker/version.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/Mkbootstrap.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Any.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_OS2.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Unix.pm
cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_VMS.pm
cpan/IO-Compress/lib/Compress/Zlib.pm
cpan/IO-Compress/lib/File/GlobMapper.pm
cpan/IO-Compress/lib/IO/Compress/Base/Common.pm
cpan/IO-Compress/lib/IO/Compress/Base.pm
cpan/IO-Compress/lib/IO/Compress/Deflate.pm
cpan/IO-Socket-IP/lib/IO/Socket/IP.pm
cpan/IO-Zlib/Zlib.pm
cpan/libnet/lib/Net/FTP/A.pm
cpan/Math-Complex/lib/Math/Complex.pm
cpan/Math-Complex/lib/Math/Trig.pm
cpan/Memoize/Memoize/ExpireFile.pm
cpan/Memoize/Memoize/Expire.pm
cpan/Memoize/Memoize/ExpireTest.pm
cpan/Memoize/Memoize/NDBM_File.pm
cpan/Memoize/Memoize.pm
cpan/Memoize/Memoize/SDBM_File.pm
cpan/Memoize/Memoize/Storable.pm
cpan/Memoize/t/array_confusion.t
cpan/Memoize/t/array.t
cpan/Memoize/t/correctness.t
cpan/Memoize/t/errors.t
cpan/Memoize/t/expfile.t
cpan/Memoize/t/expire.t
cpan/Memoize/t/expmod_n.t
cpan/Memoize/t/expmod_t.t
cpan/Memoize/t/flush.t
cpan/Memoize/t/normalize.t
cpan/Memoize/t/prototype.t
cpan/Memoize/t/speed.t
cpan/Memoize/t/tiefeatures.t
cpan/Memoize/t/tie_gdbm.t
cpan/Memoize/t/tie_ndbm.t
cpan/Memoize/t/tie_sdbm.t
cpan/Memoize/t/tie_storable.t
cpan/Memoize/t/tie.t
cpan/Memoize/t/unmemoize.t
cpan/MIME-Base64/Base64.pm
cpan/MIME-Base64/QuotedPrint.pm
cpan/Module-Loaded/lib/Module/Loaded.pm
cpan/Module-Load/lib/Module/Load.pm
cpan/Module-Metadata/lib/Module/Metadata.pm
cpan/PerlIO-via-QuotedPrint/lib/PerlIO/via/QuotedPrint.pm
cpan/Pod-Simple/lib/Pod/Simple/BlackBox.pm
cpan/Pod-Simple/lib/Pod/Simple/DumpAsText.pm
cpan/Pod-Simple/lib/Pod/Simple/DumpAsXML.pm
cpan/Pod-Simple/lib/Pod/Simple/HTMLLegacy.pm
cpan/Pod-Simple/lib/Pod/Simple/LinkSection.pm
cpan/Pod-Simple/lib/Pod/Simple.pm
cpan/Pod-Simple/lib/Pod/Simple/Progress.pm
cpan/Pod-Simple/lib/Pod/Simple/PullParser.pm
cpan/Pod-Simple/lib/Pod/Simple/PullParserToken.pm
cpan/Scalar-List-Utils/lib/Scalar/Util.pm
cpan/Sys-Syslog/Syslog.pm
cpan/Test-Simple/lib/Test2/API.pm
cpan/Test-Simple/lib/Test2/Tools/Tiny.pm
cpan/Test-Simple/lib/Test2/Util.pm
cpan/Test-Simple/lib/Test2/Util/Trace.pm
cpan/Test-Simple/lib/Test/Builder/IO/Scalar.pm
cpan/Text-Balanced/lib/Text/Balanced.pm
cpan/Text-Tabs/lib/Text/Tabs.pm
cpan/Text-Tabs/lib/Text/Wrap.pm
cpan/Tie-RefHash/t/refhash.t
cpan/Time-Piece/Piece.pm
cpan/version/lib/version.pm
```
I believe this is an incorrect approach.  We should be testing these files to see whether they conform to our current version of Perl 7 semantics.  Testing whether they still conform to Perl 5 semantics as well should be done in checkouts from their version control systems.  Only by unambiguously run these files against Perl 7 semantics can we hope to flush out all the problems that a major version upgrade will face.

I propose to write a program which writes the Markdown needed to create these tickets.  The intro and outro of the program will guide potential new contributors.

Thank you very much.
Jim Keenan

$ ack '^use [pv]5;' cpan/ | wc -l
108

**Comment by atoomic** [comment]
1. cpan modules

The idea is to patch modules in that branch before submitting fixes upstreams.
We need to keep in mind that changes need to work with all supported versions upstream which is probably 5.8+ in most cases.

So this is legitimate to open tickets for each distro. Ideally if we could tag them using something like `dual life` or `cpan`

2. Using `p5` in some cpan files

Originally the idea was to publish `p5` to `CPAN` but I'm not sure we need it anymore.
We need to confirm if using `use v5` is good enough and working.
But yes we need to fix these files so they could work in both world p5 and p7.

**Comment by jkeenan** [comment]
This ticket is fairly moot at this point.  We got all modules under `cpan/` and `dist/` to work with strict-by-default and, on that basis, we've been submitting pull requests upstream to CPAN maintainers on an as-needed basis.  We will presumably do that with warnings-by-default and other objectives as well.  So we have practices that are, at least for the time being, satisfactory.

Closing ticket.
