### ISSUE TITLE
regen/pX.pl relies on miniperl

### ISSUE THREAD

**Issue by atoomic** [atoomic/perl#128]
This has some pros and cons, but the fact that regen/pX.pl relies on miniperl avoid parsing the existing .h files to get the feature bits... but also introduce a chicken and egg issue...
We probably want to revisit it... 

Maybe we do not need it and should merge to regen/features.pl

**Comment by jkeenan** [comment]
> This has some pros and cons, but the fact that regen/pX.pl relies on miniperl avoid parsing the existing .h files to get the feature bits... but also introduce a chicken and egg issue...
> We probably want to revisit it...
> 
> Maybe we do not need it and should merge to regen/features.pl

The files in question are no longer in the repository, so the ticket is moot.  Closing.
