### ISSUE TITLE
dist/Storable/t/integer.t: one last warning

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#135]
As of 398d4caf4b, `dist/Storable/t/integer.t` is passing all tests but throwing this warning:
```
Hexadecimal number > 0xffffffff non-portable at (eval 8) line 1.
../dist/Storable/t/integer.t .. ok
All tests successful.
Files=1, Tests=875,  0 wallclock secs ( 0.04 usr  0.01 sys +  0.13 cusr  0.01 csys =  0.19 CPU)
Result: PASS
```

**Comment by atoomic** [comment]
the `local $^W` is incorrect and too late
we can simply use `no warnings 'portable';` as this is also working in 5.6

```
╰─> perl -w -e 'print "$]\n"; use warnings; no warnings "portable"; my $x = 0xffffffff; '
5.006
```

need to submit fixes upstream once we have all the fixes in

**Comment by jkeenan** [comment]
> As of [398d4ca](https://github.com/atoomic/perl/commit/398d4caf4b1192c6c2137439d1faa50f5a4cc8dc), `dist/Storable/t/integer.t` is passing all tests but throwing this warning:
> 
> ```

Any remaining warnings will be addressed as part of Objective 3 work.  So we can close this ticket for now.
