### ISSUE TITLE
alpha Objective 1: Bumping the Major Version Number

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#152]
**Objective:** Bump the Perl major version number wherever needed in the code base.

No other guts changes except those needed to implement this objective.

No changes in the test suite except for a few test files which (probably incorrectly) assume that Perl's major version was fixed for all time at 5.

**Acceptance Criteria:** The Perl test suite, modified only to accommodate limitations described above, runs GREEN in all major configurations and on all major operating systems for which we can test.

**Comment by atoomic** [comment]
there is a second subtask after this one:
change `/perl5/` path to `/perl7/` path

**Comment by jkeenan** [comment]
On 7/24/20 8:07 PM, Nicolas R. wrote:
> there is a second subtask after this one:
> change |/perl5/| path to |/perl7/| path
> 

Where in the distribution does that need to be done?

jimk

**Comment by atoomic** [comment]
Many files, including default values from configuration are using `perl5/` in PATH.
`git grep 'perl5/'` gives an idea which files are impacted

Running `perl -V` show for example several locations (but this is not limited to these)
```
> perl -V
....
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/7.0.0/darwin-2level
    /usr/local/lib/perl5/site_perl/7.0.0
    /usr/local/lib/perl5/7.0.0/darwin-2level
    /usr/local/lib/perl5/7.0.0
```

**Comment by atoomic** [comment]
Pending work lives here https://github.com/atoomic/perl/pull/169

**Comment by jkeenan** [comment]
Based on conversations with @atoomic , we are now in the final stages of work on Objective 1, "Bumping the Major Version Number."  I will soon be applying tag `alpha-01-MC-1` to branch `alpha-dev-01-bump-version`.  That will mean "Merge Candidate" 01 -- in effect, our **second** candidate for merging into the `alpha` branch.

By creating this tag, we are stating to ourselves that we expect no further commits to the `alpha-dev-01-bump-version` branch and that it is ready for various forms of testing outside the confines of the machines we personally control.  Anyone can grab the code at this tag, create testing configurations for the code and report data from those tests back to us.

We will examine the test data as it becomes available over the next 1-3 days.  Unless there are significant contraindications that require new commits to the `alpha-dev-01-bump-version` branch, we will then merge the branch into the mainline `alpha` branch, tag the main branch `alpha-01`, and start work on [Objective 2](https://github.com/atoomic/perl/issues/153).

@toddr 

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Per discussion, with @atoomic, we have done sufficient work on bumping Perl's major version number to warrant merging our objective branch into `alpha` and deeming Objective 1 complete.

This was completed in this commit:
```
commit 800f84ad070df976fd5e07a60968328a254c15f6 (HEAD -> alpha, tag: alpha-01, 
upstream/alpha-dev-02-strict, upstream/alpha, origin/alpha-dev-02-strict, 
origin/alpha, alpha-dev-02-strict)
Author:     ☢ ℕicolas ℝ <nicolas@atoomic.org>
AuthorDate: Mon Aug 3 17:05:56 2020
Commit:     James E Keenan <jkeenan@cpan.org>
CommitDate: Fri Aug 7 07:55:36 2020
```
Tag `alpha-01` was applied to the `alpha` branch at this commit to signal the completion of Objective 1.

We will now proceed to [Objective 2](https://github.com/atoomic/perl/issues/153).

@atoomic, could you write a comment to this ticket summarizing the major aspects of this bump in perl's major version number?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
Sumup of the main challenges during the version bump (in no specific order)
- Porting tools not ready to bump to version != 5
- internal having hard coded version to 5 in many locations
- XS check using incomplete version check: internal and dual life module (version is one of them, Time-HiRes, Storable, threads... )
- Devel-PPPort issue for ppport.h not acceptation any other major version than 5
- introducing the version semantic... and compare macro to solve the D-PPP issue

Here are the issues we discovered during this iteration:
https://github.com/atoomic/perl/issues?q=is%3Aopen+label%3A%22CPAN+issue%22+label%3A%22Version+Bump%22+

Here is a tracker of the known CPAN issues discovered:
https://github.com/toddr/perl-modernization/issues?q=is%3Aissue+is%3Aopen+label%3A%22Major+Version%22
