### ISSUE TITLE
[doc] Doc for using the new compare macro

### ISSUE THREAD

**Issue by atoomic** [atoomic/perl#174]
We need to document and recommend the usage of the new compare macros

We also want to point the issues when converting old code to use the new compare functions

example:
```
PERL_VERSION < 9         => PERL_VERSION_LT(5,9,0)
PERL_VERSION <= 9       => PERL_VERSION_LT(5,10,0) // maybe PERL_VERSION_LE(5,9,'*')
PERL_VERSION > 9         => PERL_VERSION_GT(5,10,0) // maybe PERL_VERSION_GE(5,9,'*');
PERL_VERSION >= 9      => PERL_VERSION_GE(5,9,0)
```

copy: @toddr, @khwilliamson

**Comment by atoomic** [comment]
you can view more examples from https://github.com/atoomic/perl/pull/169/files#diff-bf2b4b4cae742ff4fdb486063e83106e

**Comment by khwilliamson** [comment]
Isn't this closable?

**Comment by atoomic** [comment]
yes we can clearly close this case 
the work is already in alpha branch
