### ISSUE TITLE
Objective 01a: use v5/6/7

### ISSUE THREAD

**Issue by atoomic** [atoomic/perl#187]
Objective:
- restore use 5.x behavior
- block `use >= 5.33`
- block use 6 or use v6
- introduce a new behavior for use v7

View prototype from c1eb8193866dd20b8b555e336a4f7f4bcea17938

view discussion from: https://github.com/atoomic/perl/issues/153#issuecomment-671460366

Acceptance Criteria: clean test suite

**Comment by jkeenan** [comment]
> Objective:
> 
>     * restore use 5.x behavior
> 

@atoomic , can you elaborate on what is meant by "5.x behavior" here?  That is, what is the current behavior (as of the completion of Objective 1) and what are we restoring it to?

>     * block `use > 5.32.1`
> 

But what if we do a second maintenance release for 5.32, i.e., perl-5.32.2?

>     * block use 6 or use v6
> 
>     * introduce a new behavior for use v7
> 

What is the new behavior you wish to introduce for `use v7;`?
> View prototype from [c1eb819](https://github.com/atoomic/perl/commit/c1eb8193866dd20b8b555e336a4f7f4bcea17938)
> 
> view discussion from: [#153 (comment)](https://github.com/atoomic/perl/issues/153#issuecomment-671460366)
> 
> Acceptance Criteria: clean test suite

**Comment by jkeenan** [comment]
Some test files on which this work **may** have an impact:
```
t/porting/diag.t
t/comp/use.t
t/run/switches.t
```
As well as others touched in https://github.com/atoomic/perl/commit/c1eb8193866dd20b8b555e336a4f7f4bcea17938

**Comment by jkeenan** [comment]
> > Objective:
> > ```
> > * restore use 5.x behavior
> > ```
> 
> @atoomic , can you elaborate on what is meant by "5.x behavior" here? That is, what is the current behavior (as of the completion of Objective 1) and what are we restoring it to?
> 
> > ```
> > * block `use > 5.32.1`
> > ```
> 
> But what if we do a second maintenance release for 5.32, i.e., perl-5.32.2?
> 
> > ```
> > * block use 6 or use v6
> > 
> > * introduce a new behavior for use v7
> > ```
> 
> What is the new behavior you wish to introduce for `use v7;`?
> 
> > View prototype from [c1eb819](https://github.com/atoomic/perl/commit/c1eb8193866dd20b8b555e336a4f7f4bcea17938)
> > view discussion from: [#153 (comment)](https://github.com/atoomic/perl/issues/153#issuecomment-671460366)
> > Acceptance Criteria: clean test suite

Getting these questions clarified will be important in resolving questions discussed in PSC Technical meeting this morning.

Thanks.
jimk

**Comment by atoomic** [comment]
I agree we need clarification on the direction to take.

Here are the answers to your questions:

1. restore 5.x behavior: `use 5.5` which stands for `use v5.500` should also fail in Perl 7 
without any change it's not failing, as `5.500 < 7.000`, but `use 5.5` is a mistake for someone probably meaning `use v5.5`

2. in fact we should block `use >= 5.33`, if 5.34 is released then this should change to `>= 5.35`
-1- and -2- are linked each other as this is giving us the boundary to check when we see 5.*

3. `use v7`: do we want keep using `use v7.x.y` and have multiple flavors of Perl 7... 
or would we prefer using `use v7` and if needed `use experimental :8`

**Comment by jkeenan** [comment]
> I agree we need clarification on the direction to take.
> 
> Here are the answers to your questions:
> 
>     1. restore 5.x behavior: `use 5.5` which stands for `use v5.500` should also fail in Perl 7
>        without any change it's not failing, as `5.500 < 7.000`, but `use 5.5` is a mistake for someone probably meaning `use v5.5`
> 
>     2. in fact we should block `use >= 5.33`, if 5.34 is released then this should change to `>= 5.35`
>        -1- and -2- are linked each other as this is giving us the boundary to check when we see 5.*
> 
>     3. `use v7`: do we want keep using `use v7.x.y` and have multiple flavors of Perl 7...
>        or would we prefer using `use v7` and if needed `use experimental :8`

Thanks for getting back to me on this.  Do you have an estimated timeline for completion of this mini-objective?

jimk

**Comment by atoomic** [comment]
@jkeenan I can work on something for this objective 01a in a matter of a few hours,
but I really wonder if it worth the effort before we know where we are going... and I'm afraid that this is going to take weeks... 

Let me see if I can come with something clean and isolated to reach what I've in mind.
We can still massage it later.

**Comment by atoomic** [comment]
@jkeenan #189 provides the basic implementation for this case

**Comment by jkeenan** [comment]
Achieved via https://github.com/atoomic/perl/pull/189.  I have added a tag.
```
commit 9420ed5e3260fb4fcef4b50c795ac0b0b413ddb9 (HEAD -> alpha, tag: alpha-01a, upstream/alpha)
Merge: 02980c45c5 a1869a70e6
Author:     Nicolas R <atoomic@cpan.org>
AuthorDate: Wed Aug 12 16:12:34 2020 -0600
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Aug 12 16:12:34 2020 -0600
```
