### ISSUE TITLE
To quiet "Bareword not allowed while "strict subs" in use exceptions, dress the barewords

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#191]
Since we began trying to make every file run with strict-by-default, we have encountered many situations where, when we encounter code like this:
```
my ($filename, @array);
$filename = './file-to-be-tied';
tie @array, Tie::File, $filename;
```
... and we then run it against a Perl 7 executable, we get an exception like this:
```
Bareword "Tie::File" not allowed while "strict subs" in use at tie-first-attempt-at-correction.pl line 8.
tie-first-attempt-at-correction.pl had compilation errors.
```
Up until yesterday, I tended to "fix" these files by putting this code in a block and starting the block off with `no strict 'subs;`.
```
{
    no strict 'subs';
    my ($filename, @array);
    $filename = './file-to-be-tied';
    tie @array, Tie::File, $filename;
}
```
As discussed in https://github.com/atoomic/perl/issues/188 on Aug 11, we now feel that it a cleaner way to resolve this exception would be to put clothes on the bareword.  This would requiring adding only two characters, avoid the need to create a block and relax strictures.  Hence:
```
my ($filename, @array);
$filename = './file-to-be-tied';
tie @array, 'Tie::File', $filename;
```
Through judicious use of `git diff`, `grep`, and `ack` we can identify places in the codebase where I inserted `no strict 'subs'` in the hope of getting a file to run under strictures.  For example,
```
$ git diff v5.32.0..HEAD . | ack -A1 '(^(?:diff|\+.*?no strict.*?subs))' | ack -c '^\+.*?no strict.*?subs'
76
```

**Assignment** is to examine each of these files and see whether dressing the bareword with quotation marks (or, in certain cases, with `q||`) can be used instead of creating a block and suspending strictures.

Some places will be quite obvious:

    diff --git a/dist/Storable/t/tied.t b/dist/Storable/t/tied.t
    index e8be39e460..6b1cb50ac9 100644
    --
    +    no strict 'subs';
    +    $c = tie %hash, TIED_HASH;
    --
    +    no strict 'subs';
         tie $a, P; my $r = thaw freeze \$a; $b = $$r;
    --
    +    { no strict 'subs'; tie @a, TIED_ARRAY; }
         my $r = bless \@a, 'FOO99';
    --

Other places, particularly those where the `no strict 'subs'` was inserted into the text of a perl program which was then `eval`ed by the test program, will be more challenging.

**Acceptance criteria:** The coding in the files in question will be simplified and all tests that are currently passing will continue to do so.

Thank you very much.
Jim Keenan

**Comment by oodler577** [comment]
@jkeenan I am happy to take this one.

**Comment by oodler577** [comment]
```
computer:perl$ git diff --name-only v5.32.0 | egrep -i '(t|pl)$' | xargs grep -l "no strict" | wc
     218     218    5008
computer:perl$ git diff --name-only v5.32.0 | egrep -i '(t|pl)$' | xargs grep -l "no strict 'sub" | wc
      23      23     327
computer:perl$ git diff --name-only v5.32.0 | egrep -i '(t|pl)$' | xargs grep -l "no strict sub" | wc
       1       1      13
```

Getting some different numbers and easier for me to parse which files to look at. Comments, @jkeenan? In any case, it's providing me plenty of files to tackle.

**Comment by jkeenan** [comment]
This ticket has been effectively superseded by a series of individual tickets/pull requests.  So I'm closing this issue for now.  We'll open a new ticket if we think further work is needed.

Thank you very much.
Jim Keenan
