### ISSUE TITLE
Study changes to t/base files for strict-on-default

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#197]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:

```
t/base/cond.t
t/base/if.t
t/base/lex.t
t/base/num.t
t/base/pat.t
t/base/rs.t
t/base/term.t
t/base/translate.t
t/base/while.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

Thank you for helping to improve the Perl programming language.

**Comment by mdperry** [comment]
Per separate communication with @jkeenan I am taking on this ticket now.

**Comment by mdperry** [comment]
Short version: I'm satisified with the changes introduced in all the files I was asked to study.

Long version: It was very interesting to see how different developers, over the years, had created the tersest perl code possible, with the fewest explanatory comments or documentation possible, yet still test a very diverse range of functions.  

I learned some very intriguing factoids about how `$/`, the `INPUT_RECORD_SEPARATOR`, can be put to work.  All of them were indeed documented in _Programming Perl 4e_, but I had never used some of them.  

I confess that the file `t/base/lex.t` has some particularly cryptic perl program statements, which often seem to devolve into what is (or isn't) evaluated the same as the empty string `""`.  Curiously, nobody seems to be using my preferred syntax, `q{}`, as recommended in Damian Conway's _Perl Best Practices_  Be that as it may.  Also, I know precious little about how lexers and parsers work under the hood, and I decided to take the advice from _Programming Perl_ where it said something like, "Run away, run away!" (I am paraphrasing).

**Comment by jkeenan** [comment]
> Short version: I'm satisified with the changes introduced in all the files I was asked to study.
> 
> Long version: It was very interesting to see how different developers, over the years, had created the tersest perl code possible, with the fewest explanatory comments or documentation possible, yet still test a very diverse range of functions.
> 
> I learned some very intriguing factoids about how `$/`, the `INPUT_RECORD_SEPARATOR`, can be put to work. All of them were indeed documented in _Programming Perl 4e_, but I had never used some of them.
> 
> I confess that the file `t/base/lex.t` has some particularly cryptic perl program statements, which often seem to devolve into what is (or isn't) evaluated the same as the empty string `""`. Curiously, nobody seems to be using my preferred syntax, `q{}`, as recommended in Damian Conway's _Perl Best Practices_ Be that as it may. Also, I know precious little about how lexers and parsers work under the hood, and I decided to take the advice from _Programming Perl_ where it said something like, "Run away, run away!" (I am paraphrasing).

Thanks for your very thoughtful comments!
