### ISSUE TITLE
Study changes to regen/regen*.pl (2 of 2)

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#199]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:

```
regen/regen_lib.pl
regen/warnings.pl
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)

Thank you for helping to improve the Perl programming language.

**Comment by oodler577** [comment]
@jkeenan I am happy to take this one.

**Comment by oodler577** [comment]
@jkeenan :

**Changes to `regen/warnings.pl`**

Looks good. Just changed `$VERSION` to a package variable using `our`.

**Changes to `regen/regen_lib.pl`**

Suggestion:

Import `Symbol` with an empty list of subs to export. You're getting `qw(gensym ungensym qualify qualify_to_ref)` but only using `gensym` - and in a fully qualified way.

So change,

`use Symbol;`
to
`use Symbol();`

That's it. Let me know what you think and I can create a PR.

**Comment by jkeenan** [comment]
> @jkeenan :
> 
> **Changes to `regen/warnings.pl`**
> 
> Looks good. Just changed `$VERSION` to a package variable using `our`.
> 
> **Changes to `regen/regen_lib.pl`**
> 
> Suggestion:
> 
> Import `Symbol` with an empty list of subs to export. You're getting `qw(gensym ungensym qualify qualify_to_ref)` but only using `gensym` - and in a fully qualified way.
> 
> So change,
> 
> `use Symbol;`
> to
> `use Symbol();`
> 
> That's it. Let me know what you think and I can create a PR.

Yes, I think that would be okay.  Before making the p.r., (a) please run `make test_porting`; and (b) please make sure that in your ~/.git/config you have the username and email address you want listed in AUTHORS.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Touch-up to `regen/regen_lib.pl` provided in commit 7a9743b880a749ad69867a9c535738751f4d3240.  Closing this issue.

Thank you very much.
Jim Keenan
