### ISSUE TITLE
Overzealous global replace of perl7 for perl5

### ISSUE THREAD

**Issue by briandfoy** [atoomic/perl#2]
The commit 5e7cfd7cc8dbbd442ef64419ffcc7ab6c31d7922 does a global replace of perl5 to perl7, but many of the replacements are referring to specific versions of Perl. 

I think we probably need to remove this commit entirely rather than go back to remodify all of the files. At this early stage I think rewriting history isn't as disastrous as it could be.

**Comment by atoomic** [comment]
I also noticed that and already provided some `counter` fixes that should have been amended to this commit... 
I'm just concerned that removing this commit in a rebase will lead to many conflicts 

I would prefer amending it and fixing the places that should not have been massively updated

**Comment by briandfoy** [comment]
This is the sort of thing we can crowd source :)

**Comment by eiro** [comment]
hello. i think i have a very useful tool for the job (https://github.com/eiro/fixlines) so i can contribute. should i fork from the commit just before  5e7cfd7 ?

**Comment by eiro** [comment]
i started from the head of master and my workflow is

```
vim 
:r!grep -RFni perl5
:,$s#\cperl\zs5#7#cg          
```
so i think it could be quick but i need infos like

* will the repo be perl5 or perl7
* i assume the mailing lists will be untouched. correct?
* i assume the old scripts  (from perl4 to perl5) will make perl5 untouched

**Comment by briandfoy** [comment]
@eiro just start at the head of `p7`.

But, I suggest that you don't automate any of the corrections. You need to inspect each one by hand. For anything that might change (mailing list name, etc), skip it. Look for the changes that will never be correct, such as finding `perl7.8.8` when that is definitely `perl5.8.8`.

And, we don't need to get all the fixes in one go.

**Comment by eiro** [comment]
hello,

> @eiro just start at the head of `p7`.

so how to get grid of already pushed changes? can i revert them
one by one?

i'll fork just before 5e7cfd7cc8dbbd442ef64419ffcc7ab6c31d7922 and do
my best. we'll see.

> But, I suggest that you don't automate any of the corrections.
> You need to inspect each one by hand.

That's the case. fixlines just makes this easy to do. Here is my
workflow:

* `:r!grep -RFni perl5` give the list of the lines with possible
  change.
* when in doubt, i can gF to inspect the file
* when all the changes are made, i can `%!fixlines` to apply the
  changes.

> For anything that might change (mailing list name, etc), skip it.

the question was this exactly: what is supposed to change. for exemple:
will the perl5 becomes perl7?

Look for the changes that will never be correct,
such as finding `perl7.8.8` when that is definitely `perl5.8.8`.

> And, we don't need to get all the fixes in one go.

indeed.

regards
marc

**Comment by kyzn** [comment]
I can help too! @eiro, do you want to share 357 files 5e7cfd7 touches?

**Comment by atoomic** [comment]
@eiro I would suggest to work on the `HEAD` of the `p7` branch on files listed by the commit,
I will squash these commits together as long as they come

I will try to reply to your questions:
> will the repo be perl5 or perl7
- we are considering renaming the repo from `perl5` to `perl`

> i assume the mailing lists will be untouched. correct?
- correct for now we should not touch the mailing lists

> i assume the old scripts (from perl4 to perl5) will make perl5 untouched
- yes we should not touch these scripts

thanks for your contributions

**Comment by atoomic** [comment]
I've amended a few changes to 5e7cfd7cc8dbbd442ef64419ffcc7ab6c31d7922 which is now 13344ed4aa2265085b94884183a9a73b01a97225

Changes includes
- restore perl7-porter -> perl5-porter
- restore perl78 -> perl58
- perl7-porters -> perl5-porters

**Comment by eiro** [comment]
hello,

@kyzn : i read the instructions @atoomic gave me and a first batch is merged so i think i can be quick on this task. however it would be nice if you do a second pass after that ?

**Comment by eiro** [comment]
i think perl5db.pl should become perldb.pl?

**Comment by atoomic** [comment]
we could probably rename perl5db but I think this might be premature and
could be the source of many issues. I would probably leave it for later

**Comment by eiro** [comment]
done (pr available). when a old version scheme is used in documentation, should i replace it ?

example:

"I'll use the hypothetical 5.004_07 to 5.004_08 patch as an example."

becomes 

"I'll use the hypothetical 7.0.23 to 7.0.27 patch as an example."

when

"at least as far back as perl7.003_07" move back to "at least as far back as perl5.003_07"

**Comment by jkeenan** [comment]
This 

> The commit [5e7cfd7](https://github.com/atoomic/perl/commit/5e7cfd7cc8dbbd442ef64419ffcc7ab6c31d7922) does a global replace of perl5 to perl7, but many of the replacements are referring to specific versions of Perl.
> 
> I think we probably need to remove this commit entirely rather than go back to remodify all of the files. At this early stage I think rewriting history isn't as disastrous as it could be.

This problem appears to be under control, so I'm closing the ticket.

Thank you very much.
Jim Keenan
