### ISSUE TITLE
Study changes to t/cmd/*.t and t/opbasic/*.t

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#200]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:

```
t/cmd/elsif.t
t/cmd/for.t
t/cmd/mod.t
t/cmd/subval.t
t/opbasic/arith.t
t/opbasic/cmp.t
t/opbasic/concat.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)

Thank you for helping to improve the Perl programming language.

**Comment by rabbiveesh** [comment]
I would love to work on this issue.

**Comment by atoomic** [comment]
@rabbiveesh thanks for your interest, this case is now yours :-)

**Comment by jkeenan** [comment]
> I would love to work on this issue.

@rabbiveesh In light of discussion in [another ticket](https://github.com/atoomic/perl/issues/198), I'm trimming the list of files to be studied in this ticket.  Please let us know if you have any questions.

Thank you very much.
Jim Keenan

**Comment by rabbiveesh** [comment]
Everything in t/cmd/* and t/opbasic/*, as listed above, is totally correct in its strict compliance.

Some of the tests are using lexical `$a`, which I noticed got changed to `$alpha` in t/opbasic/concat.t. Is part of this goal to not use magical globals as lexicals, or is that a side issue?

**Comment by jkeenan** [comment]
> Everything in t/cmd/* and t/opbasic/*, as listed above, is totally correct in its strict compliance.
> 
> Some of the tests are using lexical `$a`, which I noticed got changed to `$alpha` in t/opbasic/concat.t. Is part of this goal to not use magical globals as lexicals, or is that a side issue?

We have been trying to replace those magical globals with better named variables, as you spotted.  This is something we decided to do only when we were a couple of weeks in to this project.

So if you'd like to submit a pull request for the remaining instances of `$a` and `$b` in your two directories, we'd gladly consider it.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> Everything in t/cmd/* and t/opbasic/*, as listed above, is totally correct in its strict compliance.
> 
> Some of the tests are using lexical `$a`, which I noticed got changed to `$alpha` in t/opbasic/concat.t. Is part of this goal to not use magical globals as lexicals, or is that a side issue?

@rabbiveesh, do you have any further comments for this ticket?  If not, we'd like to close it.  Please let us know within three days.

Thank you very much.
Jim Keenan

**Comment by rabbiveesh** [comment]
Yeah, sorry, please go ahead and close. I'll submit a PR independent of this issue.

**Comment by jkeenan** [comment]
P.r. accepted; closing ticket.

Thank you very much.
Jim Keenan
