### ISSUE TITLE
lib/sigtrap.t: blocker to strict-by-default

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#231]
As of commit ac6b7ccf73 in the alpha-dev-02-strict branch on Aug 18 2020, the file cited is failing.  Here is output from `cd t; ./perl harness -v <file>; cd -`:
```
# ../lib/sigtrap.t

# Failed test 13 - stack-trace does not try to modify read-only arguments at ./test.pl line 1080
#      got 'Caught a SIGINT at - line 5\n$ = main::__ANON__() called from file \'tmp2967A\' line 5'
# expected /(?^:\$ = main::__ANON__\(3\) called)/
# PROG: 
# 
#     BEGIN { *CORE::GLOBAL::kill = sub {} }
#     require sigtrap;
#     import sigtrap "INT";
#     sub { $SIG{INT}->("INT") } -> (3)
#   
# STATUS: 0
../lib/sigtrap.t .. 
1..16
ok 1 - at ../lib/sigtrap.t line 14
# use sigtrap
ok 2 - import excessive version number
ok 3 - send bad signame to import
ok 4 - send handler without subref
ok 5 - install normal handler
ok 6 - install the die handler
ok 7 - install traceback handler
ok 8 - check normal-signals set
ok 9 - check error-signals set
ok 10 - check old-interface-signals set
ok 11 - install custom handler
ok 12 - respect existing handler set to IGNORE
not ok 13 - stack-trace does not try to modify read-only arguments
ok 14 - should set default handler
ok 15 - does it talk with $Verbose set?
ok 16 - does handler_die() croak?
Failed 1/16 subtests 

Test Summary Report
-------------------
../lib/sigtrap.t (Wstat: 0 Tests: 16 Failed: 1)
  Failed test:  13
Files=1, Tests=16,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.02 cusr  0.01 csys =  0.04 CPU)
Result: FAIL

```

@atoomic @toddr 

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Consider the following program, which is derived from the one remaining failing test in `lib/sigtrap.t`.
```
$ cat sgtp.pl 
BEGIN { *CORE::GLOBAL::kill = sub {} }
require sigtrap;
import sigtrap "INT";
sub { $SIG{INT}->("INT") } -> (3)
```
Let's run it with Perl 5:
```
$ perl sgtp.pl 
Caught a SIGINT at sgtp.pl line 4
$ = main::__ANON__(3) called from file 'sgtp.pl' line 4
```
Now with a perl (7) built with strict-by-default:
```
$ thisperl -v | head -2 | tail -1
This is perl 7, version 0, subversion 0 (v7.0.0) built for x86_64-linux-thread-multi

$ thisperl -V | head -2 | tail -1 | cut -d ' ' -f5
0b15509d576149032885ba7a77835a6a67076c18

$ thisperl sgtp.pl 
Caught a SIGINT at sgtp.pl line 4
$ = main::__ANON__() called from file 'sgtp.pl' line 4
```
The only difference in the output is that Perl7 fails to include a number between the parentheses in the output.  But the pattern against which the output is matched in test 13 of `lib/sigtrap.t` is expecting `(3)` there.

Things that I've tried, without success:  (1) putting a `no strict` before the `BEGIN` block.  (2) Rewriting `import` as a method call on `sigtrap` rather than a function call.

So, if we could figure out why we're getting only `()` and not getting `(3)`, we could get this file to pass and be one step closer to our goal.

@atoomic, @toddr

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
I poked at it until being able to identify the real issue coming from using @DB::args
this is now fixed correctly with e495c87586b0f7204462752ac7a226d45078e35c

**Comment by jkeenan** [comment]
Consider the following program, which is exactly like the one shown in the previous comment except that we provide an empty list as the argument to the `sub` call in the final line of the program.
```
$ cat sgtp-noarg.pl 
BEGIN { *CORE::GLOBAL::kill = sub {} }
require sigtrap;
import sigtrap "INT";
sub { $SIG{INT}->("INT") } -> ()
```
Let's run it, first with Perl 5.
```
$ perl sgtp-noarg.pl 
Caught a SIGINT at sgtp-noarg.pl line 4
$ = main::__ANON__() called from file 'sgtp-noarg.pl' line 4
```
And now with the Perl 7 from the previous comment:
```
$ thisperl sgtp-noarg.pl 
Caught a SIGINT at sgtp-noarg.pl line 4
$ = main::__ANON__() called from file 'sgtp-noarg.pl' line 4
```
The two calls now produce exactly the same output.  So the question is:  Why, when we provide an argument to that `sub` call, does Perl 7 ignore it?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Fixed by @atoomic in this series of commits:

fe3702b8eb5b830187f7898918381aa1d2f2fc6a
f8c1cde3af36bb1316a19b75ae954416de2e2dc2
e6eadaa2d6b2ee5050fdab9e272764cbdbeaafa0
f84105338a4641b6b0d13bcf29c4ac31e1ab0110
e495c87586b0f7204462752ac7a226d45078e35c
