### ISSUE TITLE
lib/vars.t: blocker to strict-by-default

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#233]
As of commit ac6b7ccf73 in the alpha-dev-02-strict branch on Aug 18 2020, the file cited is failing.  Here is output from `cd t; ./perl harness -v <file>; cd -`:
```
# ../lib/vars.t

$X::p' is not a valid variable name under strict vars at ../lib/vars.t line 22.
BEGIN failed--compilation aborted at ../lib/vars.t line 22.
../lib/vars.t ..
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run

Test Summary Report
-------------------
../lib/vars.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
Result: FAIL
```

@atoomic @toddr 

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
@atoomic, @toddr,

`lib/vars.t` is a file written without any test harness functions, so it has hard-coded test numbers and most tests lack descriptions.  This makes it difficult to debug or refactor.

What I'd like to propose is that we first refactor this in Perl 5, then pull the refactored program into our alpha-02-dev-strict branch and work on it there to get it to be strict compliant.

Could you look at the version of `lib/vars.t` in the `jkeenan/lib-vars-t-20200822` branch in [Perl 5](https://github.com/Perl/perl5/blob/jkeenan/lib-vars-t-20200822/lib/vars.t)?

Now, I concede that there is one test (commented out in the above) whose purpose in the original I could not figure out.  So the test is running one short of the plan.  However, if we can resolve that problem, then I am confident that we could quickly rework it to be strict-compliant in our repo.

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
This is fixed by ed5a52ef

Enabling strict in `lib/vars.t` would require removing or adjusting many test using some invalid variable declarations.
I think it's much better to leave the original intent and disabling strict globally in this test...
otherwise we will lose all the meaning of these tests.

**Comment by jkeenan** [comment]
> This is fixed by [ed5a52e](https://github.com/atoomic/perl/commit/ed5a52efc0629f27ee86339d07b9f34106544e5f)
> 
> Enabling strict in `lib/vars.t` would require removing or adjusting many test using some invalid variable declarations.
> I think it's much better to leave the original intent and disabling strict globally in this test...
> otherwise we will lose all the meaning of these tests.

Yes, but that can be specified more explicitly and precisely with:
```
$ git diff
diff --git a/lib/vars.t b/lib/vars.t
index eca8aacaea..440e1afafa 100644
--- a/lib/vars.t
+++ b/lib/vars.t
@@ -6,7 +6,7 @@ BEGIN {
     $ENV{PERL5LIB} = '../lib';
 }
 
-use v5;
+no strict;
 use warnings;
 
 $| = 1;
```

**Comment by toddr** [comment]
I agree. `no strict;` would be better

**Comment by atoomic** [comment]
add `no strict` via 4d592f19fb484f51e1c0a1704dcadfc71dfaa470

**Comment by jkeenan** [comment]
> add `no strict` via [4d592f1](https://github.com/atoomic/perl/commit/4d592f19fb484f51e1c0a1704dcadfc71dfaa470)

Thanks.  All tests passing. Closing ticket.
