### ISSUE TITLE
t/op/coreamp.t: blocker to strict-by-default

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#238]
As of commit ac6b7ccf73 in the alpha-dev-02-strict branch on Aug 18 2020, the file cited is failing.  Here is output from `cd t; ./perl harness -v <file>; cd -`:
```
# t/op/coreamp.t

Global symbol "$file" requires explicit package name (did you forget to declare "my $file"?) at op/coreamp.t line 701.
BEGIN not safe after errors--compilation aborted at op/coreamp.t line 776.
op/coreamp.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
op/coreamp.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.02 CPU)
Result: FAIL
```
Probably encountered a rabbit hole once I started to properly scope those variables.

@atoomic @toddr 

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
this is fixed by 5c796da83c722841c71fe1b408a330b14dd4fae9 but this probably needs a review

**Comment by jkeenan** [comment]
> this is fixed by [5c796da](https://github.com/atoomic/perl/commit/5c796da83c722841c71fe1b408a330b14dd4fae9) but this probably needs a review

@atoomic, for review of `t/op/coreamp.t`, I figured it would be better to compare HEAD to the state of that same file in the `alpha` branch, as the latter is unchanged from the `v5.32.0` tag in Perl 5 blead.  So the diffs below are cross-branch (actually, cross directory, with different checkouts in each directory) rather than from the last previous commit in the same branch.

I think the changes that need to be examined fall into three cases.

**Case 1:** Replacement of old-style subroutine call with call of method `can`

The first 3 instances cited below occur with the definition of the file's `sub test_proto`.

There is some inline documentation before that sub definition:
```
# This tests that the &{} syntax respects the number of arguments implied
# by the prototype, plus some extra tests for the (_) prototype.
```

Well, if we're changing to a method call, are we not violating the original intent of the tests as expressed in that comment? (47ac839d7e6 (Father Chrysostomos 2011-08-26))

(Note that I ask that with regret, because otherwise I like the change.)

```diff
63,64c65,66
<     eval " &CORE::$o(1) ";
<     like $@, qr/^Too many arguments for $o at /, "&$o with too many args";
---
>     eval " CORE->can('$o')->(1) ";
>     like $@, qr/^Too many arguments for $o at /, "&$o with too many args ; line:" . __LINE__;

84,85c84,85
<     is &{"CORE::$o"}($in), $out, "&$o";
<     lis [&{"CORE::$o"}($in)], [$out], "&$o in list context";
---
>     is( CORE->can("$o")->($in), $out, "&$o " . __LINE__ );
>     lis( [ CORE->can("$o")->($in) ], [$out], "&$o in list context" );
88c88
<     is &{"CORE::$o"}(), $out, "&$o with no args";
---
>     is( CORE->can("$o")->($in), $out, "&$o with no args" );

1175,1178c1191,1194
<       $tests ++;
<       ok   exists &{"my$word"}
<         || (eval{&{"CORE::$word"}}, $@ =~ /cannot be called directly/),
<      "$word either has been tested or is not ampable";
---
>       $main::tests ++;
>       ok( exists &{"my$word"}
>         || (eval{CORE->can($word)->() }, $@ =~ /cannot be called directly/),
>      "$word either has been tested or is not ampable" ) or warn "$word either has been tested or is not ampabl: $@";
```

**Case 2:** Manipulation of variable being tested

Can you explain (to someone unfamiliar with evalbytes) you're making in lines 512-513 in your version?
```
507,508c511,513
<   chop(my $upgraded = "use utf8; $U_100_bytes" . chr 256);
<   is &myevalbytes($upgraded), chr 256, '&evalbytes';
---
>   chop(my $upgraded = "use utf8; { no strict; $U_100_bytes" . chr 256);
>   $upgraded .= " }";
>   is( &myevalbytes($upgraded), chr 256, '&evalbytes [myevalbytes]' );
```
**Case 3:** Use of hint bit

In this case you've replaced all but the `strict->import;` call.  Again, can you explain this to someone ignorant of both evalbytes and hint bits?

```
511,514c516,522
<   strict->import;
<   &myevalbytes('
<     is someone, "someone", "run-time hint bits do not leak into &evalbytes"
<   ');
---
>   strict->import; # cannot use strict to check hints
>   my $hint_bit = 0x20000; # use an arbitrary bit
>   $^H |= $hint_bit;
>   my $x = &myevalbytes('my $x; BEGIN { $x = $^H } $x');
>   is( $x & $hint_bit, 0, "run-time hint bits do not leak into &evalbytes" );
>   $^H |= ~$hint_bit; # remove the bit
> 
```

I'm not saying these changes are wrong (yet).   This is just far from my usual territory.

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
Case1:
The test itself is named `coreamp`... so you are right maybe we slightly change the intent of the test
I mainly call the functions without the need of `&$sub`.
I would have to think more about this

Case 2:
`$U_100_bytes` does not pass strict, so I isolated it in a scope without strict

Case 3: Use of hint bit
strict is stored in hint, and the test was checking that enabling strict at run time does not leak to evalbytes...
but now that strict is enabled by default we cannot use `strict` for this test
I just used a`HINT_LOCALIZE_HH` which is used in many tests

**Comment by jkeenan** [comment]
> Case1:
> The test itself is named `coreamp`... so you are right maybe we slightly change the intent of the test
> I mainly call the functions without the need of `&$sub`.
> I would have to think more about this
> 

Agreed.  Here's where we have to ask, *"What was Father C thinking?"* ;-)

> Case 2:
> `$U_100_bytes` does not pass strict, so I isolated it in a scope without strict
> 
> Case 3: Use of hint bit
> strict is stored in hint, and the test was checking that enabling strict at run time does not leak to evalbytes...
> but now that strict is enabled by default we cannot use `strict` for this test
> I just used a`HINT_LOCALIZE_HH` which is used in many tests

Okay, I understand your rationale for cases 2 and 3.  So only case 1 is left to think about.

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
For `Case 1`, I would prefer an extra review, maybe @toddr ?

**Comment by toddr** [comment]
> For `Case 1`, I would prefer an extra review, maybe @toddr ?

How? where?

**Comment by jkeenan** [comment]
> > For `Case 1`, I would prefer an extra review, maybe @toddr ?
> 
> How? where?

See the concern I raised as "Case 1" in [this earlier comment in this ticket](https://github.com/atoomic/perl/issues/238#issuecomment-675749899).  Essentially, was the code change subtly changing what was being tested?

**Comment by toddr** [comment]
I would say any switch to can is a change in what's being tested and should be put back.

**Comment by jkeenan** [comment]
> I would say any switch to can is a change in what's being tested and should be put back.

@atoomic, can you address the concern which @toddr and I have discussed here?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I would say any switch to can is a change in what's being tested and should be put back.
> 
> @atoomic, can you address the concern which @toddr and I have discussed here?
> 
> Thank you very much.
> Jim Keenan

It turns out that, with judicious use of `no strict 'refs';`, we can preserve the original syntax and preserve the original intent of the tests.  See: 1a8e330659

Thank you very much.
Jim Keenan
