### ISSUE TITLE
Study changes to t/porting (1 of 2)

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#241]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:
```
t/test.pl
t/thread_it.pl
t/porting/FindExt.t
t/porting/args_assert.t
t/porting/bench_selftest.t
t/porting/bincompat.t
t/porting/checkcase.t
t/porting/checkcfgvar.t
t/porting/copyright.t
t/porting/corelist.t
t/porting/customized.dat
t/porting/customized.t
t/porting/diag.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  (1) Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)  (2) You should subscribe to this repository so that you get email updates.

Thank you for helping to improve the Perl programming language.

**Comment by brainbuz** [comment]
I'll take it

**Comment by brainbuz** [comment]
fresh_perl.t executes scripts from a data section denoted by an __END__ instead of __DATA__ delimiter.
When strict is disabled globally one test fails. The failure is that an extra space is appended to a string in a test.
In addition several of these tests specify use strict.

```perl
# Failed test 23 - at ./test.pl line 1069
#      got "TIEARRAY FAKEARRAY fred\nTIEARRAY FAKEARRAY fred\nDESTROY "
# expected "TIEARRAY FAKEARRAY fred\nTIEARRAY FAKEARRAY fred\nDESTROY"
# PROG: 
#    {
#        package FAKEARRAY;
# 
#        my $count = 0;
#        sub TIEARRAY
#        { print "TIEARRAY @_\n";
#          die "bomb out\n" unless $count ++ ;
#          bless ['foo']
#        }
#        sub FETCH { print "fetch @_\n"; $_[0]->[$_[1]] }
#        sub STORE { print "store @_\n"; $_[0]->[$_[1]] = $_[2] }
#        sub DESTROY { print "DESTROY \n"; undef @{$_[0]}; }
#    }
```

**Comment by brainbuz** [comment]
Several of these files have issues or concerns worth looking at, fresh_perl fails without strict. Others have todo or strict blocks for other active issue or old systems.


file | pass | strictures not globally specified | reviewed diffs |  
-- | -- | -- | -- | --
t/run/cloexec.t | x | x | x |  
t/run/dtrace.t |   | no dtrace | x | skipped no dtrace
t/run/exit.t | x | x | x |  
t/run/flib/broken.pm |   | x |   | module is intended to be broken under strict
t/run/fresh_perl.t | x | fail | x | Strict @17, 2x near 500 in code writing to external script, 2x near 700, near 775, 820. fails without global stricture.
t/run/locale.t | x | x | x |  
t/run/runenv.t | x | x |   | Open todo for https://github.com/Perl/perl5/pull/18095
t/run/script.t | x | x | x |  
t/run/switchF1.t | x | x | x |  
t/run/switchI.t | x | x | x | most of test is in skip, delete perhaps?
t/run/switchM.t | x | x | x |  
t/run/switchd-78586.t | x | x | x |  
t/run/switches.t | x | x | x | todo for VMS, is this still a supported platform?
t/run/switcht.t | x | x | x |  
t/run/switchx.t | x | x | x |

**Comment by jkeenan** [comment]
> Several of these files have issues or concerns worth looking at, fresh_perl fails without strict. Others have todo or strict blocks for other active issue or old systems.
> file 	pass 	strictures not globally specified 	reviewed diffs 	 
> t/run/cloexec.t 	x 	x 	x 	 
> t/run/dtrace.t 	  	no dtrace 	x 	skipped no dtrace
> t/run/exit.t 	x 	x 	x 	 
> t/run/flib/broken.pm 	  	x 	  	module is intended to be broken under strict
> t/run/fresh_perl.t 	x 	fail 	x 	Strict @17, 2x near 500 in code writing to external script, 2x near 700, near 775, 820. fails without global stricture.
> t/run/locale.t 	x 	x 	x 	 
> t/run/runenv.t 	x 	x 	  	Open todo for [Perl/perl5#18095](https://github.com/Perl/perl5/pull/18095)
> t/run/script.t 	x 	x 	x 	 
> t/run/switchF1.t 	x 	x 	x 	 
> t/run/switchI.t 	x 	x 	x 	most of test is in skip, delete perhaps?
> t/run/switchM.t 	x 	x 	x 	 
> t/run/switchd-78586.t 	x 	x 	x 	 
> t/run/switches.t 	x 	x 	x 	todo for VMS, is this still a supported platform?
> t/run/switcht.t 	x 	x 	x 	 
> t/run/switchx.t 	x 	x 	x

1. VMS is still a supported platform, so any TODOS related to it stay.

2. I don't get any failures for `t/run/fresh_perl.t` in the `alpha` branch.  Could you post what failures you're getting and provide output of `./perl -Ilib -Vconfig_args`?

3. I suspect we probably can remove `use strict;` from the approx. 9 unit tests where it's found in `t/run/fresh_perl.t`.  Removing those lines -- as distinct from merely commenting them out -- might require changes in the `EXPECT` portions of those unit tests because the expected line number would change.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> Several of these files have issues or concerns worth looking at, fresh_perl fails without strict. Others have todo or strict blocks for other active issue or old systems.
> file 	pass 	strictures not globally specified 	reviewed diffs 	 
> t/run/cloexec.t 	x 	x 	x 	 
> t/run/dtrace.t 	  	no dtrace 	x 	skipped no dtrace
> t/run/exit.t 	x 	x 	x 	 
> t/run/flib/broken.pm 	  	x 	  	module is intended to be broken under strict
> t/run/fresh_perl.t 	x 	fail 	x 	Strict @17, 2x near 500 in code writing to external script, 2x near 700, near 775, 820. fails without global stricture.
> t/run/locale.t 	x 	x 	x 	 
> t/run/runenv.t 	x 	x 	  	Open todo for [Perl/perl5#18095](https://github.com/Perl/perl5/pull/18095)
> t/run/script.t 	x 	x 	x 	 
> t/run/switchF1.t 	x 	x 	x 	 
> t/run/switchI.t 	x 	x 	x 	most of test is in skip, delete perhaps?
> t/run/switchM.t 	x 	x 	x 	 
> t/run/switchd-78586.t 	x 	x 	x 	 
> t/run/switches.t 	x 	x 	x 	todo for VMS, is this still a supported platform?
> t/run/switcht.t 	x 	x 	x 	 
> t/run/switchx.t 	x 	x 	x

I just noticed that you provided data about `t/run/*.t` in a ticket where the request was to study certain files in `t/porting`.  Can you clarify?

Thank you very much.
Jim Keenan

**Comment by brainbuz** [comment]
Had several tickets open in browser and updated the wrong one, while trying to finish my updates before going to bed. I'll copy the updates to the right one.

**Comment by brainbuz** [comment]
Here is the result of my work on this ticket. The diag test file has a large number of failing todos, which suggests it could use some review. Otherwise this group is good to go.

file | pass | strictures not globally specified | reviewed diffs |  
-- | -- | -- | -- | --
t/test.pl | --- | x | x | not a test, a utility used to run other tests.
t/thread_it.pl | --- | x | x | this is another utility for testing.
t/porting/FindExt.t | x | x | x |  
t/porting/args_assert.t | x | x | x |  
t/porting/bench_selftest.t | x | x | x |  
t/porting/bincompat.t | x | x | x |  
t/porting/checkcase.t | x | x | x |  
t/porting/checkcfgvar.t | x | x | x |  
t/porting/copyright.t | x | x | x |  
t/porting/corelist.t | x | x | x |  
t/porting/customized.dat | --- | --- | --- | data for customized.t, not a test
t/porting/customized.t | x | --- | x |  
t/porting/diag.t | x | x | x | large number of failing todos

**Comment by jkeenan** [comment]
> Here is the result of my work on this ticket. The diag test file has a large number of failing todos, which suggests it could use some review. Otherwise this group is good to go.

Indeed.  However, performing major surgery on any test file is P5P's job -- not ours. ;-)

I take it that any changes *we* made in these files were non-controversial in your review, so I'm closing this ticket.  Thanks again for your thorough work.
