### ISSUE TITLE
Study changes to t/porting (2 of 2)

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#242]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:
```
t/porting/dual-life.t
t/porting/exec-bit.t
t/porting/extrefs.t
t/porting/manifest.t
t/porting/pending-author.t
t/porting/perlfunc.t
t/porting/re_context.t
t/porting/readme.t
t/porting/regen.t
t/porting/ss_dup.t
t/porting/test_bootstrap.t
t/porting/utils.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  (1) Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)  (2) You should subscribe to this repository so that you get email updates.

Thank you for helping to improve the Perl programming language.

**Comment by brainbuz** [comment]
I can take a few more of these.

**Comment by brainbuz** [comment]
One minor issue found PR  #298

file | pass | strictures removed | reviewed diffs | notes
-- | -- | -- | -- | --
t/porting/dual-life.t | x | x | x |  
t/porting/exec-bit.t | x | x | x |  
t/porting/extrefs.t | x | x | x |  
t/porting/manifest.t | x | x | x |  
t/porting/pending-author.t | x | x | x |  
t/porting/perlfunc.t | x | x | x |  
t/porting/re_context.t | x | x | x |  
t/porting/readme.t | x | x | x |  
t/porting/regen.t | x | x | x |  
t/porting/ss_dup.t | x | x | x |  
t/porting/test_bootstrap.t | x | --- | x |  
t/porting/utils.t | x | x | x |
