### ISSUE TITLE
Study changes to t/run/*.t

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#246]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:
```
t/run/cloexec.t
t/run/dtrace.t
t/run/exit.t
t/run/flib/broken.pm
t/run/fresh_perl.t
t/run/locale.t
t/run/runenv.t
t/run/script.t
t/run/switchF1.t
t/run/switchI.t
t/run/switchM.t
t/run/switchd-78586.t
t/run/switches.t
t/run/switcht.t
t/run/switchx.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  (1) Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)  (2) You should subscribe to this repository so that you get email updates.

Thank you for helping to improve the Perl programming language.

**Comment by brainbuz** [comment]
I'll take it

**Comment by brainbuz** [comment]
file | pass | strictures not globally specified | reviewed diffs |  
-- | -- | -- | -- | --
t/run/cloexec.t | x | x | x |  
t/run/dtrace.t |   | no dtrace | x | skipped no dtrace
t/run/exit.t | x | x | x |  
t/run/flib/broken.pm |   | x |   | module is intended to be broken under strict
t/run/fresh_perl.t | x | fail | x | Strict @17, 2x near 500 in code writing to external script, 2x near 700, near 775, 820. fails without global stricture.
t/run/locale.t | x | x | x |  
t/run/runenv.t | x | x |   | Open todo for Perl/perl5#18095
t/run/script.t | x | x | x |  
t/run/switchF1.t | x | x | x |  
t/run/switchI.t | x | x | x | most of test is in skip, delete perhaps?
t/run/switchM.t | x | x | x |  
t/run/switchd-78586.t | x | x | x |  
t/run/switches.t | x | x | x | todo for VMS, is this still a supported platform?
t/run/switcht.t | x | x | x |  
t/run/switchx.t | x | x | x |

**Comment by brainbuz** [comment]
```perl
# Failed test 23 - at ./test.pl line 1069
#      got "TIEARRAY FAKEARRAY fred\nTIEARRAY FAKEARRAY fred\nDESTROY "
# expected "TIEARRAY FAKEARRAY fred\nTIEARRAY FAKEARRAY fred\nDESTROY"
# PROG: 
#    {
#        package FAKEARRAY;
# 
#        my $count = 0;
#        sub TIEARRAY
#        { print "TIEARRAY @_\n";
#          die "bomb out\n" unless $count ++ ;
#          bless ['foo']
#        }
#        sub FETCH { print "fetch @_\n"; $_[0]->[$_[1]] }
#        sub STORE { print "store @_\n"; $_[0]->[$_[1]] = $_[2] }
#        sub DESTROY { print "DESTROY \n"; undef @{$_[0]}; }
#    }
```

**Comment by brainbuz** [comment]
Jim here's the output  ./perl -Ilib -V config_args. @INC includes default paths which don't exist because the perl is uninstalled.

The test fails when I remove the global stricture.

[config_args.txt](https://github.com/atoomic/perl/files/5301009/config_args.txt)

**Comment by jkeenan** [comment]
> Jim here's the output ./perl -Ilib -V config_args. @inc includes default paths which don't exist because the perl is uninstalled.
> 
> The test fails when I remove the global stricture.
> 
> [config_args.txt](https://github.com/atoomic/perl/files/5301009/config_args.txt)

Can you check to see whether you accidentally deleted a trailing whitespace after `DESTROY` at line 186 of `t/run/fresh_perl.t`?

If you have deleted that spaceband, that will explain the test failure.  Note that at line 177, there is a whitespace after `DESTROY` and before the newline character.  Why? 'Cause that's the way a certain Mr. Wall wrote it back in October 1994!

**Comment by brainbuz** [comment]
My editor seems to like to cleanup whitespace, when I edited the file with vi to comment out use strict the test was able to pass.

**Comment by jkeenan** [comment]
> My editor seems to like to cleanup whitespace, when I edited the file with vi to comment out use strict the test was able to pass.

So if you're thinking of a p.r. (drawn against `alpha`) I'd suggest you remove all the `use strict;` statements (I think there are 10 of them), then adjust the line numbers in the EXPECT parts to suit.

**Comment by jkeenan** [comment]
One file updated in https://github.com/atoomic/perl/pull/289.  Closing.

Thank you very much.
Jim Keenan
