### ISSUE TITLE
Study changes to t/uni/*.t (1 of 2)

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#247]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:
```
t/uni/bless.t
t/uni/caller.t
t/uni/eval.t
t/uni/fold.t
t/uni/goto.t
t/uni/gv.t
t/uni/method.t
t/uni/overload.t
t/uni/package.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  (1) Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)  (2) You should subscribe to this repository so that you get email updates.

Thank you for helping to improve the Perl programming language.

**Comment by brainbuz** [comment]
I'll take it.

**Comment by brainbuz** [comment]
file | pass | strictures not globally specified | reviewed diffs |  
-- | -- | -- | -- | --
t/uni/bless.t | x | x | x |  
t/uni/caller.t | x | x | x |  
t/uni/eval.t | x | x | x |  
t/uni/fold.t | x | x | x |  
t/uni/goto.t | x | x | x |  
t/uni/gv.t | x | x | x |  
t/uni/method.t | x | --- | x | strict at line 13
t/uni/overload.t | x | --- | x | strict at line 15
t/uni/package.t | x | x | x |

**Comment by jkeenan** [comment]
Looks good.  Closing ticket.

Thank you very much.
Jim Keenan
