### ISSUE TITLE
Study changes to t/uni/*.t (2 of 2)

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#248]
In this ticket we will study our progress in pursuit of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153), for the following files in the Perl core distribution:
```
t/uni/parser.t
t/uni/select.t
t/uni/sprintf.t
t/uni/stash.t
t/uni/tie.t
t/uni/tr_utf8.t
t/uni/universal.t
t/uni/variables.t
t/uni/write.t
```
These files should be evaluated in light of the guidelines presented on [this wiki page](https://github.com/atoomic/perl/wiki/How-to-Start-Working-with-Tests-in-the-Perl-Core-Distribution).  Please post the summary of your findings in a single comment in this issue.

**First-time contributors:**  (1) Please post a comment to this ticket indicating you are working on it.  That will enable us to assign the ticket to you.  (GitHub won't let us do that until it already thinks you're part of the project.)  (2) You should subscribe to this repository so that you get email updates.

Thank you for helping to improve the Perl programming language.

**Comment by brainbuz** [comment]
I'll take this one.

**Comment by brainbuz** [comment]
file | pass | strictures not globally specified | reviewed diffs |  
-- | -- | -- | -- | --
t/uni/parser.t | x | --- | x | global stricture enabled after last test
t/uni/select.t | x | x | x |  
t/uni/sprintf.t | x | x | x |  
t/uni/stash.t | x | --- | x | Line 51 enables strict for 1 test when it should already be on.
t/uni/tie.t | x | x | x |  
t/uni/tr_utf8.t | x | x | x |  
t/uni/universal.t | x | x | x |  
t/uni/variables.t | x | x | x |  
t/uni/write.t | x | --- | x | strict at beginning of file.

**Comment by jkeenan** [comment]
I screwed up the first pass at merging this code.  https://github.com/atoomic/perl/commit/117a21e7fbf9a97bebc9073e0d86381c7c44815c should now be in the `alpha` branch.
