### ISSUE TITLE
t/run/runenv.t: Intermittent failures in test 65 re PERL_PERTURB_KEYS

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#250]
In commit e49c7da013 I have added to the alpha-dev-02-strict branch a file
called `t/run/xrunenv.t` which is a reduction of a section of `t/run/runenv.t`
which is intermittently failing.

When you run `t/run/runenv.t` and get a failure, the output looks like this:
```
$ cd t;./perl harness run/runenv.t; cd -
run/runenv.t .. 14/112 # Failed test 65 - PERL_PERTURB_KEYS = 2 allows one to recreate a random hash at run/runenv.t line 287
#      got "XUBIKRWEAFLDZCMPQVHTYJSGNO"
# expected "WRKEBIXUDFLAHVQMCZPONGSJYT"
run/runenv.t .. Failed 1/112 subtests 
```
When you run the reduction file, you will frequently get a failure in its test 5.
```
$ ./perl -Ilib t/run/xrunenv.t 
1..6
ok 1 - PERL_PERTURB_KEYS = 0 allows one to recreate a random hash
ok 2 - Got the same debug output when we set PERL_HASH_SEED and PERL_PERTURB_KEYS
ok 3 - PERL_PERTURB_KEYS = 1 results in different key order with the same key
ok 4 - Got the same debug output when we set PERL_HASH_SEED and PERL_PERTURB_KEYS
not ok 5 - PERL_PERTURB_KEYS = 2 allows one to recreate a random hash
# Failed test 5 - PERL_PERTURB_KEYS = 2 allows one to recreate a random hash at t/run/xrunenv.t line 85
#      got "RMEQUTOLVHGYNDZWBAISCFJKPX"
# expected "GYDNWZTUMQEROHLVCJFXPKBSIA"
ok 6 - Got the same debug output when we set PERL_HASH_SEED and PERL_PERTURB_KEYS
```
When I run this file 20 times, it PASSes between 11 and 16 times and FAILs
between 9 and 4 times.

I can, if it helps, provide a P7 program I wrote to capture the output of
this, but you shouldn't really need it.

There was a thread about PERL_PERTURB_KEYS recently in perl5.porters, but
there doesn't appear to have been any change to blead as a result.

How can we deal with these intermittent failures?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
The issue described here are not specific to Perl 7 and can be reproduce using blead or Perl 5.30 for example.
Going to investigate what s wrong with this test.

**Comment by atoomic** [comment]
I think I got it correctly, going to add a unit test to show the issue
and an extra commit with the fix candidate and would ask a review upstream

I've the feeling that you discovered a bug

**Comment by atoomic** [comment]
I'm going to open a case upstream to show the issue and submit the fix for it.

**Comment by atoomic** [comment]
@jkeenan the discussion is now moved upstream, we should close this case with the revert performed by 1bd8ddef
