### ISSUE TITLE
ext/ and dist/*/hints.pl files should be strict-compliant

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#251]
Under `dist/` and `ext/` there are 72 OS-specific "hints.pl" files which are used in the compilation of modules that have XS code.
```
$ ack 'hints\/.*?\.pl' MANIFEST | cut -d '        ' -f1 | head
cpan/DB_File/hints/bitrig.pl
cpan/DB_File/hints/dynixptx.pl
cpan/DB_File/hints/minix.pl
cpan/DB_File/hints/netbsd.pl
cpan/DB_File/hints/openbsd.pl
cpan/DB_File/hints/sco.pl
cpan/Digest-MD5/hints/dec_osf.pl
cpan/Digest-MD5/hints/irix_6.pl
cpan/Digest-MD5/hints/MacOS.pl
cpan/IPC-SysV/hints/cygwin.pl
```
Since these files contain Perl programs, they must be compliant with strict-by-default.  Generally speaking, they are not.  This causes a warning to be emitted during `make`.  For example, on FreeBSD, we get the following when `make` encounters `ext/POSIX/hints/freebsd.pl`:
```
$ zgrep  -C3 'not imported' maketp.ef0410a531.freebsd.threaded.output.txt.gz
cc  -shared  -L/usr/local/lib -fstack-protector-strong  Opcode.o  -o ../../lib/auto/Opcode/Opcode.so        
chmod 755 ../../lib/auto/Opcode/Opcode.so
./miniperl -Ilib make_ext.pl lib/auto/POSIX/POSIX.so  MAKE="make" LIBPERL_A=libperl.a LINKTYPE=dynamic
Variable "$self" is not imported at hints/freebsd.pl line 3.
Global symbol "$self" requires explicit package name (did you forget to declare "my $self"?) at hints/freebsd.pl line 3.
Warning (mostly harmless): No library found for -lposix
Warning (mostly harmless): No library found for -lcposix
```
I don't yet have evidence that this causes a fundamental problem -- but my approach to build-time warnings is that they indicate a defect in one's understanding of the build process -- a defect cured by eliminating the cause of the warning.

It appears that these warnings are no longer emitted if I insert a `no strict 'vars';` statement before the first line of code in such a hints file.

Does this seem like a valid approach?

@atoomic @toddr

I will supply a pull request that demonstrates this for linux and freebsd.

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
`use v5` is an alternate solution to also mark these files as not compliant for now.
`no strict 'vars'` is an ok solution and honestly this could be improved later if needed

**Comment by jkeenan** [comment]
Merge of 255 should take care of this ticket.  Closing.
