### ISSUE TITLE
alpha objective 2a: restricting to 'use v7' should not be done.

### ISSUE THREAD

**Issue by toddr** [atoomic/perl#263]
A windows bug cropped up which basically boiled down to the fact that we're erroring when one does `require 7.000000`.

This should be allowed and it is a mistake that we have not adopted the patch in this branch. 

The error message that should not exist in perl is:

```
C:\perl\t>"C:\perl\perl.exe" -IC:\perl\perl.exe -le "require 7.000000; print qq{VER_OK}"
use v7; is the only supported syntax for Perl 7. at -e line 1.
```

@atoomic already has a patch for this. it just needs to go into the strict branch. We also need to remove all of the work arounds we've put into this branch to overcome this.

**Comment by atoomic** [comment]
This a change in the behavior introduced as part of objective 01 #152
This should not target the objective 02 for strict #153,
I suggest we perform that change at the beginning of warnings objective #154

**Comment by jkeenan** [comment]
On 9/2/20 12:43 PM, Todd Rinaldo wrote:
> A windows bug cropped up which basically boiled down to the fact that 
> we're erroring when one does |require 7.000000|.
> 
> This should be allowed and it is a mistake that we have not adopted the 
> patch in this branch.
> 
> The error message that should not exist in perl is:
> 
> |C:\perl\t>"C:\perl\perl.exe" -IC:\perl\perl.exe -le "require 7.000000; 
> print qq{VER_OK}" use v7; is the only supported syntax for Perl 7. at -e 
> line 1. |
> 
> @atoomic <https://github.com/atoomic> already has a patch for this. it 
> just needs to go into the strict branch. We also need to remove all of 
> the work arounds we've put into this branch to overcome this.

Can you list those workarounds?

**Comment by jkeenan** [comment]
On 9/2/20 12:46 PM, ℕicolas ℝ. wrote:
> This a change in the behavior introduced as part of objective 01 #152 
> <https://github.com/atoomic/perl/issues/152>
> This should not target the objective 02 for strict #153 
> <https://github.com/atoomic/perl/issues/153>,
> I suggest we perform that change at the beginning of warnings objective 
> #154 <https://github.com/atoomic/perl/issues/154>
> 

What we can do is after we merge alpha-dev-02-strict into alpha, we can 
fork an alpha-dev-02a-repair branch in which we address this problem, 
create merge candidates as needed, and when they are ready, merge one 
into alpha and only then fork an 'alpha-dev-03-warnings' branch.

jimk

**Comment by jkeenan** [comment]
@toddr, how we proceed depends, IMO, in large part on what those "workarounds" you mentioned earlier actually are.

If I understand you correctly, this commit:
```
$ gitshowf 55a6a9445ccc89766c2f311c055be144f70039e6
commit 55a6a9445ccc89766c2f311c055be144f70039e6
Author:     Todd Rinaldo <toddr@cpan.org>
AuthorDate: Wed Sep 2 11:33:16 2020 -0500
Commit:     Todd Rinaldo <toddr@cpan.org>
CommitDate: Wed Sep 2 12:30:58 2020 -0500

    Windows doesn't have the version set to 7

diff --git a/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Unix.pm b/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Unix.pm
index 33836141ce..d3a902fdfa 100644
--- a/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Unix.pm
+++ b/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MM_Unix.pm
@@ -1145,7 +1145,7 @@ WARNING
         }
     }
 
-    if ( $ver && $ver eq '7' ) {
+    if ( $ver && $ver =~ m/^7/ ) {
         $ver = 'v7';
     }
 
```
... which is currently in the `jkeenan/gha-258-win32-20200901` branch but is **distinct** from all the other commits which you and @atoomic have been doing there for Windows-readiness.

If that is correct, then what I recommend we do is to (i) extract that commit from that branch; (ii) fork a new branch off `alpha` and cherry-pick that commit into that branch; (iii) let that branch just sit there until we get Objective 2 wrapped up; (iv) make that branch our Objective 2a and work on it as I described earlier in this ticket.

But recommendations (i) thru (iv) assume the workarounds are inconsequential.  So we need to know where we have done those workarounds and what we have to undo.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> On 9/2/20 12:43 PM, Todd Rinaldo wrote: A windows bug cropped up which basically boiled down to the fact that we're erroring when one does |require 7.000000|. This should be allowed and it is a mistake that we have not adopted the patch in this branch. The error message that should not exist in perl is: |C:\perl\t>"C:\perl\perl.exe" -IC:\perl\perl.exe -le "require 7.000000; print qq{VER_OK}" use v7; is the only supported syntax for Perl 7. at -e line 1. | @atoomic <https://github.com/atoomic> already has a patch for this. it just needs to go into the strict branch. We also need to remove all of the work arounds we've put into this branch to overcome this.
> Can you list those workarounds?

@toddr we're close to wrapping up our work on Objective 2 and merging our working branch back into `alpha`.  If we're going to perform the work you recommend above as "objective 2a", can you list the workarounds, describe the effects of the problem and provide some acceptance criteria?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
I've got a branch with these changes `alpha-dev-02-strict+v7`
still need to adjust a few failures

**Comment by jkeenan** [comment]
On 9/4/20 4:05 PM, ℕicolas ℝ. wrote:
> I've got a branch with these changes |alpha-dev-02-strict+v7|
> still need to adjust a few failures
> 

So that's what you've been up to ;-)

However, I still don't understand the problem well enough to compose an 
"Objective 2a" ticket for this.  I'd like to do this so that six months 
down the road we understand why we did it.

jimk

**Comment by atoomic** [comment]
The main issue is that during `objective 01` to bump the major version from 5 to 7,
I've added a restriction not allowing any other syntax than `use v7` (when the first digit is a 7)
the goal is to make it more relax and still allow `use v7.0`, `use v7.1`.... and co
several tests are doing something like `use $]` for example

**Comment by atoomic** [comment]
The Pull Request #265 fixes the concern there

**Comment by toddr** [comment]
This should be reverted. 
```
cpan/ExtUtils-Constant/t/Constant.t
```

**Comment by jkeenan** [comment]
> This should be reverted.
> 
> ```
> cpan/ExtUtils-Constant/t/Constant.t
> ```

Can you describe why?

Thank you very much.
Jim Keenan

**Comment by toddr** [comment]
Yes. the change seems to have clearly been made to support use v7. I suspect there are more like this. It was made in a1869a70e68a9312fb8a74978fa42b262039d843 though which might include all of them.

**Comment by jkeenan** [comment]
With the completion of [Objective 2, "strict-by-default"](https://github.com/atoomic/perl/issues/153) tonight, we are ready to begin work on Objective 2a.

I have created the following branch in our repository to hold our work on this objective:

[alpha-dev-02a-restricting](https://github.com/atoomic/perl/tree/alpha-dev-02a-restricting)

@atoomic, @toddr:  Please commit whatever work you've been doing toward this objective into this new branch.

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
@jkeenan I pushed two commits to this branch in order to relax the `use vX` syntax to satisfy this micro objective.

- fdeb46bd099d49d85c333218823a25eb17de45cb Restore use v7.x behavior
- fbf85d4894935cd819957ccb3ec3e35333e47d12 Revert change to ExtUtils-Constant/t/Constant.t

**Comment by jkeenan** [comment]
On 9/21/20 7:19 PM, ℕicolas ℝ. wrote:
> @jkeenan <https://github.com/jkeenan> I pushed two commits to this 
> branch in order to relax the |use vX| syntax to satisfy this micro 
> objective.
> 

Thanks.  I'll create a Merge Candidate and perform outside testing 
within the next 24 hours.

jimk

**Comment by jkeenan** [comment]
On 9/21/20 7:19 PM, ℕicolas ℝ. wrote:
> @jkeenan <https://github.com/jkeenan> I pushed two commits to this 
> branch in order to relax the |use vX| syntax to satisfy this micro 
> objective.
> 

Clarification:  Are these the two commits you were referring to?

commit fbf85d4894935cd819957ccb3ec3e35333e47d12 (HEAD -> 
alpha-dev-02a-restricting, upstream/alpha-
dev-02a-restricting)

commit fdeb46bd099d49d85c333218823a25eb17de45cb

And do you expect to make any further commits to this branch (assuming 
no test failures)?

Thanks again.
jimk

**Comment by jkeenan** [comment]
> @jkeenan I pushed two commits to this branch in order to relax the `use vX` syntax to satisfy this micro objective.
> 
>     * [fdeb46b](https://github.com/atoomic/perl/commit/fdeb46bd099d49d85c333218823a25eb17de45cb) Restore use v7.x behavior
> 
>     * [fbf85d4](https://github.com/atoomic/perl/commit/fbf85d4894935cd819957ccb3ec3e35333e47d12) Revert change to ExtUtils-Constant/t/Constant.t

@toddr, In satisfaction of Objective 2a, are you okay with these two commits?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
@jkeenan this is indeed the two commits I'm talking about and do not expect to push any additional changes
- fdeb46bd099d49d85c333218823a25eb17de45cb Restore use v7.x behavior
- fbf85d4894935cd819957ccb3ec3e35333e47d12 Revert change to ExtUtils-Constant/t/Constant.t

**Comment by toddr** [comment]
looks right.

**Comment by jkeenan** [comment]
I have tagged this branch as "alpha-02a-MC-1" at commit fbf85d4894935cd819957ccb3ec3e35333e47d12.  Please conduct any outside testing that you can.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
I have merged this branch into `alpha` and deleted it from the repository.  We can now proceed to [Objective 3, warnings-by-default](https://github.com/atoomic/perl/issues/154).

Thank you very much.
Jim Keenan
