### ISSUE TITLE
Test: status in core-p7 branch

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#27]
In this ticket we will track our core-p7 progress on `dist/Test`.

As of the morning of Jul 08 2020, we are getting this output from `make test` for this distro.

```
t/../dist/Test/t/05_about_verbose .................................. Global symbol "$indent" requires explicit package name (did you forget to declare "my $indent"?) at t/05_about_verbose.t line 59.
Global symbol "$indent" requires explicit package name (did you forget to declare "my $indent"?) at t/05_about_verbose.t line 60.
Execution of t/05_about_verbose.t aborted due to compilation errors.
FAILED--expected 2 tests, saw 0
t/../dist/Test/t/fail .............................................. ok
t/../dist/Test/t/mix ............................................... ok
t/../dist/Test/t/multiline ......................................... ok
t/../dist/Test/t/onfail ............................................ ok
t/../dist/Test/t/qr ................................................ ok
t/../dist/Test/t/skip .............................................. ok
t/../dist/Test/t/success ........................................... ok
t/../dist/Test/t/todo .............................................. ok


```
These results were generated on an unthreaded build on Linux.  The results might differ significantly if run on a threaded build.  There have been subsequent commits to this branch which may have impacted these results.  YMMV.

**Comment by atoomic** [comment]
fixing the `05_about_verbose` via 5c04cae86ddb5d53121b46a5ef9c52c990f94944

**Comment by atoomic** [comment]
I think all other tests are ok and we can probably close this ticket
I had a doubt with `t/multiline.t` but both are tags as todo
`1..2 todo 1 2;`

**Comment by jkeenan** [comment]
> I think all other tests are ok and we can probably close this ticket
> I had a doubt with `t/multiline.t` but both are tags as todo
> `1..2 todo 1 2;`

Yes, as of v5.32.0-576-g9e5ecda8ae, Test is testing clean.  Thanks for your effort.
