### ISSUE TITLE
Time-HiRes: status in core-p7 branch

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#28]
In this ticket we will track our core-p7 progress on `dist/Time-HiRes`.

As of the morning of Jul 08 2020, we are getting this output from `make test` for this distro.

```
t/../dist/Time-HiRes/t/alarm ....................................... Bareword found where operator expected at t/alarm.t line 39, near "new POSIX::SigAction"
	(Do you need to predeclare new?)
syntax error at t/alarm.t line 39, near "new POSIX::SigAction"
Execution of t/alarm.t aborted due to compilation errors.
# Looks like your test exited with 255 just after 1.
FAILED--expected 10 tests, saw 1
t/../dist/Time-HiRes/t/clock ....................................... ok
t/../dist/Time-HiRes/t/gettimeofday ................................ ok
t/../dist/Time-HiRes/t/itimer ...................................... ok
t/../dist/Time-HiRes/t/nanosleep ................................... ok
t/../dist/Time-HiRes/t/sleep ....................................... ok
t/../dist/Time-HiRes/t/stat ........................................ ok
t/../dist/Time-HiRes/t/time ........................................ ok
t/../dist/Time-HiRes/t/tv_interval ................................. ok
t/../dist/Time-HiRes/t/ualarm ...................................... ok
t/../dist/Time-HiRes/t/usleep ...................................... ok
t/../dist/Time-HiRes/t/utime ....................................... ok


```
These results were generated on an unthreaded build on Linux.  The results might differ significantly if run on a threaded build.  There have been subsequent commits to this branch which may have impacted these results.  YMMV.

**Comment by atoomic** [comment]
a8d2f623 is fixing the indirect call from `t/alarm.t` we can probably close this ticket

**Comment by jkeenan** [comment]
> [a8d2f62](https://github.com/atoomic/perl/commit/a8d2f62356930098f1c7d700ceca048c5309f811) is fixing the indirect call from `t/alarm.t` we can probably close this ticket

I'll review the status of each of these tickets tomorrow.  Thanks.

**Comment by jkeenan** [comment]
> [a8d2f62](https://github.com/atoomic/perl/commit/a8d2f62356930098f1c7d700ceca048c5309f811) is fixing the indirect call from `t/alarm.t` we can probably close this ticket

Yes, Time-HiRes is testing clean as of v5.32.0-576-g9e5ecda8ae.  Thanks for your investigation.
