### ISSUE TITLE
Make this repo eligible for hacktoberfest

### ISSUE THREAD

**Issue by rabbiveesh** [atoomic/perl#299]
As per a recent [blog post](http://blogs.perl.org/users/neilb/2020/10/opt-in-your-cpan-repos-for-hacktoberfest.html) on BPO, you need to opt in your repos for hacktoberfest. Could you do so for this repo?

I believe you just need to add the hacktoberfest label to the repo.

**Comment by jkeenan** [comment]
We were otherwise in October, so no action was taken.  Closing ticket.
