### ISSUE TITLE
IRC p7-dev commit bot no longer working

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#341]
Certain Github Actions designed to bot-print messages in irc.perl.org #p7-dev are failing.  As a consequence, no bot messages (commits, pull requests, etc.) are appearing in our IRC channel.

See, for example:

https://github.com/atoomic/perl/pull/340/checks?check_run_id=1508203401

https://github.com/atoomic/perl/pull/340/checks?check_run_id=1508202333

@atoomic, can you take a look?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
Thanks James for reporting it I see what is the issue I will fix it soon.

**Comment by atoomic** [comment]
@jkeenan this is fixed with 1d3a401271dec0efb110697efc54198dc9b78d51
make sure to merge / cherry pick that commit to your branch

**Comment by jkeenan** [comment]
> @jkeenan this is fixed with [1d3a401](https://github.com/atoomic/perl/commit/1d3a401271dec0efb110697efc54198dc9b78d51)
> make sure to merge / cherry pick that commit to your branch

@atoomic, Is there some reason why you merged this into `alpha-dev-03-warnings` rather than into `alpha`?

Looking at the code in the patch, I don't see anything that is specific to warnings.

I ask in part because I want to merge https://github.com/atoomic/perl/pull/340 into `alpha`, and rebasing other branches would be simpler if we first got everything into `alpha` that needs to be there.

Can you clarify?

**Comment by atoomic** [comment]
@jkeenan just by mistake I was trying to find the current development branch
this is now cherry picked to alpha via ad7546b29ce6d3b065210399b73aa7b94371fdd8
