### ISSUE TITLE
t/op/coreamp.t: Fails to compile against miniperl

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#351]
Today in our `alpha` branch I had occasion to run `make minitest`.  I got two test failures, the second of which was in `t/op/coreamp.t`.
```
$ gitcurr
alpha
$ ./miniperl -Ilib t/op/coreamp.t 
Bareword "File::Spec::Functions::updir" not allowed while "strict subs" in use at t/op/coreamp.t line 1176.
Execution of t/op/coreamp.t aborted due to compilation errors.
```
If, however, you do a full build (`make test_prep`) and then run this test file, it compiles and runs as expected.

I will submit a pull request that enables the file to compile and run as expected against both `miniperl` and `perl`.

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
Thanks a lot @jkeenan

**Comment by jkeenan** [comment]
Resolved via p.r. https://github.com/atoomic/perl/pull/352.  Closing ticket.
