### ISSUE TITLE
The `require Config; import Config;` pattern

### ISSUE THREAD

**Issue by jkeenan** [atoomic/perl#84]
*[This is a question which I first raised via email to @atoomic and others on
July 06.  I got some feedback from @atoomic, but also got some once I posted a
pull request the same day.  Now that we have this issue tracker, I would like
re-pose the question in a more systematic way.]*

The `require Config; import Config;` pattern

`require Config; import Config;` -- or a variation with `Config->import` -- is a pattern frequently seen in blead.
```
ack -l 'require\s+Config;\s*(import\s+Config|Config->import)' ./ | wc -l
202

$ ack -l 'require\s+Config;\s*(import\s+Config|Config->import)' ./ | sort | cut -d '/' -f1 | uniq -c
     38 cpan
    100 dist
     18 ext
      7 lib
     12 os2
     26 t
      1 utils
```
This pattern is so frequent that I believe that at one point it must have been considered "standard operating procedure."

Here is an example from the test suite:
```
$ head -n 12 ext/File-Glob/t/basic.t
#!./perl

BEGIN {
    chdir 't' if -d 't';
    @INC = '../lib';
    require Config; import Config;
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
        print "1..0\n";
        exit 0;
    }
}
use strict;
```
The file does not call `use strict;` until after the `BEGIN` block.  (In many similar cases, it does not call `use strict;` at all.)  It does not call for warnings at all, either through `#!./perl -w`, through `local $^W = 1;` or through `use warnings;`.  The `BEGIN` block `require`s and `import`s `Config` rather than saying `use Config;`.  The `BEGIN` block exists for the purpose of testing whether some condition has been met which would obviate the need to proceed with the rest of the file.

If I run this on blead, it's completely uneventful.
```
$ cd t;./perl harness ../ext/File-Glob/t/basic.t; cd -
../ext/File-Glob/t/basic.t .. ok     
All tests successful.
Files=1, Tests=49,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.09 cusr  0.02 csys =  0.14 CPU)
Result: PASS
```
Suppose I modify the file to run with warnings:
```
$ head -n 12 ext/File-Glob/t/wbasic.t
#!./perl -w

BEGIN {
    chdir 't' if -d 't';
    @INC = '../lib';
    require Config; import Config;
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
        print "1..0\n";
        exit 0;
    }
}
use strict;
```
When I run it, one warning is emitted, but otherwise it's still uneventful.
```
$ cd t;./perl harness ../ext/File-Glob/t/wbasic.t; cd -
../ext/File-Glob/t/wbasic.t .. 1/49 Useless use of getpwuid in void context at ../ext/File-Glob/t/wbasic.t line 115.
../ext/File-Glob/t/wbasic.t .. ok     
All tests successful.
Files=1, Tests=49,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.06 cusr  0.01 csys =  0.08 CPU)
Result: PASS
```
Now suppose that I run the unmodified file against perl in the `core-p7` branch.
```
$ cd t;./perl harness ../ext/File-Glob/t/basic.t; cd -
Global symbol "%Config" requires explicit package name (did you forget to declare "my %Config"?) at ../ext/File-Glob/t/basic.t line 7.
BEGIN not safe after errors--compilation aborted at ../ext/File-Glob/t/basic.t line 11.
../ext/File-Glob/t/basic.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 

Test Summary Report
-------------------
../ext/File-Glob/t/basic.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.02 usr +  0.00 sys =  0.02 CPU)
Result: FAIL
```
The file fails to compile.  In the `core-p7` branch, the file is being run
with strict-by-default.[1]

My first approach to remedying this failure was to delete `require Config; import Config;` and substitute `use Config;`.[2]  
```
$ git checkout ext-core-p7-20200705
Switched to branch 'ext-core-p7-20200705'
Your branch is up to date with 'origin/ext-core-p7-20200705'.

$ head -n 12 ext/File-Glob/t/basic.t
#!./perl

BEGIN {
    chdir 't' if -d 't';
    @INC = '../lib';
    use Config;
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
        print "1..0\n";
        exit 0;
    }
}
use Test::More tests => 49;

```
Running this, I get:
```
$ cd t;./perl harness ../ext/File-Glob/t/basic.t; cd -
../ext/File-Glob/t/basic.t .. ok     
All tests successful.
Files=1, Tests=49,  1 wallclock secs ( 0.01 usr  0.01 sys +  0.12 cusr  0.02 csys =  0.16 CPU)
Result: PASS
```
The file once again runs completely uneventfully.

However, having gotten this far I still had two questions:

1. Why, when strictures are on, does `require Config; import Config;` throw a fatal error while `use Config;` does not?

2. If the `require Config; import Config;` pattern was once "standard
   operating procedure" or "best practice," then perhaps there's something amiss with substituting `use Config;` for it as I did above.

In responding to my concerns, @atoomic had two different suggestions.

**1st @atoomic suggestion**
```
our %Config; # <--- just add this
BEGIN {
... # setup INC
require Config; Config->import;
}
```
Running it:
```
cd t;./perl harness -v ../ext/File-Glob/t/basic-atoomic1.t; cd -

ok 1 - use File::Glob;
Useless use of getpwuid in void context at ../ext/File-Glob/t/basic.t line 116.
ok 2 - Did not find glob() function in File::Glob
...
ok 49 - <> in list context under :bsd_glob
ok
All tests successful.
Files=1, Tests=49,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.06 cusr  0.01 csys =  0.09 CPU)
Result: PASS
```
So the file compiles and runs to completion (though displaying the expected warning).

**2nd @atoomic suggestion**
```
our %Config;
BEGIN {
    unshift @INC, './lib';
}
use Config;
```
Running it:
```
$ cd t;./perl harness -v ../ext/File-Glob/t/basic-atoomic2.t; cd -

ok 1 - use File::Glob;
Useless use of getpwuid in void context at ../ext/File-Glob/t/basic-atoomic2.t line 111.
ok 2 - Did not find glob() function in File::Glob
...
ok 49 - <> in list context under :bsd_glob
ok
All tests successful.
Files=1, Tests=49,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.06 cusr  0.00 csys =  0.08 CPU)
Result: PASS
```
So both @atoomic suggestions allow the file to run.  But I find them problematic.  Let me take the second case first.

In the second case, we've eliminated most of the code in the `BEGIN` block that gives us the flexibility to run from either the top-level directory of the `t/` directory.  We've also eliminated the code that permits the file to quickly `exit` if we haven't built with File::Glob.

It also happens that if, in the second case, you simply comment out `our %Config;` the file runs to completion.  So in the second case that statement is doing nothing.

In the first case, however, I think we're cheating a bit.  When we say `our %Config;` before the `BEGIN` block, we're simply declaring a package-level variable that just happens to have the same name as the `Config` **module** found in `lib/Config.pm`.  That module starts out:
```
package Config;
use strict;
use warnings;
our ( %Config, $VERSION );
```
So when, in the original version of the file, we say:
```
    require Config; Config->import;
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
```
... we are referring to what if fully qualified would be `%Config::Config` -- are we not?  (I believe that this is similar to what @grinnz had to say in (commenting on a pull request)[https://github.com/Perl/perl5/pull/17943#discussion_r450948540].

So I am confused about what the best way to deal with this will be.

Thank you very much.
Jim Keenan

[1] This file is underneath `ext/`, which only contains code maintained and released by Perl 5 Porters.  No code underneath `ext/` is "dual-lifed.  In the `core-p7` branch -- though perhaps not in a future "real" Perl 7 -- in such a file we don't need to account for **both** Perl 5 and Perl 7 syntax.  The `use strict;` declaration at line 12 is now irrelevant and can be removed.
[2] I also suppressed the one warning mentioned earlier.

**Comment by Grinnz** [comment]
The primary distinction between `require Config; Config->import;` and `use Config;` is that the former happens at runtime and the latter at parse time. This is even true if it is within a BEGIN block; the `use` statement will execute before the rest of the BEGIN block.

This is important in this case because importing from Config is what defines the `%Config` hash in the current package. However, this has to be done at parse time to satisfy strict 'vars'. So the runtime `Config->import` is not soon enough to satisfy strict 'vars' regarding usage of `%Config` within that same BEGIN block, even if it comes first, because it is at runtime.

Since `%Config` is a simple imported variable, fully referencing `%Config::Config` refers to the same hash, so is a perfectly reasonable workaround that doesn't rely on the variable being imported for strict 'vars' to know about.

`our %Config;` simply sets up the lexical `%Config` variable to refer to `%main::Config`, so that strict 'vars' knows about it, but after the runtime `Config->import` this package variable now references `%Config::Config`. This works perfectly fine as long as the runtime import occurs before the runtime usage. In this case, the `our` declaration just serves to tell strict what `%Config` means in the following code - a package variable, which doesn't have meaning quite yet.

**Comment by jkeenan** [comment]
@grinnz, thank you for taking the time to look at this again.

Let me just back up a minute to try to clarify my premises and objectives.

First, for the sake of discussion, I want to set aside all the controversy over `use v5;` and `use v7;`.  If it helps to talk about how code like this might be written in _"a future version of Perl"_ rather than in _"Perl 7"_, then let's do so.

I am trying to write code that assumes that strictures and warnings are on by default and that those settings are "just there."  They don't require `use strict; use warnings;` as they would in Perl 5.  They don't even require `use v7;`.  This is what is currently the case in the (soon-to-be-renamed) `core-p7` branch -- even if this will not be the case in any `perl-7.0.0`.

I am also trying to write code that respects what the people who wrote these tests more than twenty years ago were trying to accomplish.  They were writing tests where they needed to know information about how a particular `perl` executable had been configured and built.  They had various reasons for needing that information.
* They needed to know `%Config::Config` data to determine whether to run a test file at all or bomb out immediately.

* They needed to know `%Config::Config` data to determine whether to run or skip a particular unit test.

* They needed to know `%Config::Config` data to determine the conditions under which a particular unit test might pass or fail.

`ext/File-Glob/t/basic.t` actually demonstrates the first two of these three cases.

Suppose that instead of working on `core-p7` I had an assignment to modify all tests underneath `ext/` in perl-5.32.0 to run with `use strict;` right from the beginning, i.e., `use strict` had to appear right after the shebang line.  How would I modify test files to satisfy this requirement and make the fewest possible changes farther on in the file to satisfy stricture?

In the case of perl-5.32.0, I think the following code would satisfy those requirements:
```
diff --git a/ext/File-Glob/t/basic.t b/ext/File-Glob/t/basic.t
index d23ec7499b..50d3ce9de7 100644
--- a/ext/File-Glob/t/basic.t
+++ b/ext/File-Glob/t/basic.t
@@ -1,15 +1,14 @@
 #!./perl
-
+use strict;
+use Config;
 BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
-    require Config; import Config;
     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
         print "1..0\n";
         exit 0;
     }
 }
-use strict;
 use Test::More tests => 49;
 BEGIN {use_ok('File::Glob', ':glob')};
 use Cwd ();
```
The code now obeys strictures from the onset.  We `use Config;` before the `BEGIN` block.  But we still use the `BEGIN` block to get `%Config::Config` data needed to determine whether to proceed further or not.

Now let's suppose that I wanted to accomplish the same thing in this future version of perl where strictures are on by default.  (A future version of perl that happens to coincide with the `core-p7` branch at the moment.)  There I can write:
```
diff --git a/ext/File-Glob/t/basic.t b/ext/File-Glob/t/basic.t
index 8b67ba4b76..924b4f3072 100644
--- a/ext/File-Glob/t/basic.t
+++ b/ext/File-Glob/t/basic.t
@@ -1,15 +1,14 @@
 #!./perl
 
+use Config;
 BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
-    require Config; Config->import;
     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
         print "1..0\n";
         exit 0;
     }
 }
-use strict;
 use Test::More tests => 49;
 BEGIN {use_ok('File::Glob', ':glob')};
 use Cwd ();
```
I `use Config;` before the `BEGIN` block, obviating the need for the `require` within that block.  But I still use the block to determine whether to proceed onwards or not.

Now if I were to diff "perl 5.32 with 'use strict' from the beginning" versus "future perl with strict-by-default", I would get:
```
$ diff ext/File-Glob/t/basic.t ../perl-atoomic/ext/File-Glob/t/basic.t
2c2
< use strict;
---
> 
```
Only one line of difference between the two perls -- and that difference being an entirely predictable and unsurprising one.

It therefore seems to me that the best way forward in this hypothetical future version that happens to be in development in `core-p7` would be:

* `use Config;` before a `BEGIN` block.
* No more need to `require` or `import` Config within that `BEGIN` block.
* But retain the `BEGIN` block for its original purpose:  accessing `%Config::Config` data to determine whether to continue running the file or not.

What do you think?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
if `@INC` is setup before `require Config` you cannot convert it to a `use Config`, as this will not load try to load from the expected location, and you should simply add `our %Config` before the `BEGIN` block.
If there is not `@INC` setup (note this can be done using setup_inc helper) then it's safe to convert it to a `use`

In case of doubt adding `our %Config` is the correct way to go.

**Comment by atoomic** [comment]
say it differently 

This is wrong
```diff
diff --git a/ext/File-Glob/t/basic.t b/ext/File-Glob/t/basic.t
index 8b67ba4b76..924b4f3072 100644
--- a/ext/File-Glob/t/basic.t
+++ b/ext/File-Glob/t/basic.t
@@ -1,15 +1,14 @@
 #!./perl
 
+use Config;
 BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
-    require Config; Config->import;
     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
         print "1..0\n";
         exit 0;
     }
 }
-use strict;
 use Test::More tests => 49;
 BEGIN {use_ok('File::Glob', ':glob')};
 use Cwd ();
```

**Comment by jkeenan** [comment]
On 7/10/20 6:03 PM, Nicolas R. wrote:
> if |@INC| is setup before |require Config| you cannot convert it to a 
> |use Config|, as this will not load try to load from the expected 
> location, and you should simply add |our %Config| before the |BEGIN| block.
> If there is not |@INC| setup (note this can be done using setup_inc 
> helper) then it's safe to convert it to a |use|
> 

I kinda understand what you're saying there, but ...

> In case of doubt adding |our %Config| is the correct way to go.
> 

That just says "code smell" to me.

jimk

**Comment by jkeenan** [comment]
How about this (for future Perl/`core-p7`) instead?
```
$ head -n 14 ext/File-Glob/t/basic.t
#!./perl

BEGIN {
    chdir 't' if -d 't';
    @INC = '../lib';
    no strict 'vars';
    require Config; Config->import;
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
        print "1..0\n";
        exit 0;
    }
}
use Test::More tests => 49;
BEGIN {use_ok('File::Glob', ':glob')};
```
The diff from what's currently in `core-p7` would be:
```
diff --git a/ext/File-Glob/t/basic.t b/ext/File-Glob/t/basic.t
index 8b67ba4b76..73124876fb 100644
--- a/ext/File-Glob/t/basic.t
+++ b/ext/File-Glob/t/basic.t
@@ -3,13 +3,13 @@
 BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
+    no strict 'vars';
     require Config; Config->import;
     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
         print "1..0\n";
         exit 0;
     }
 }
-use strict;
 use Test::More tests => 49;
 BEGIN {use_ok('File::Glob', ':glob')};
 use Cwd ();
```
The difference between "perl-5.32+use-strict-from-the-beginning" to this would be:
```
[perl] 543 $ diff ext/File-Glob/t/basic.t ../perl-atoomic/ext/File-Glob/t/basic.t
2,3c2
< use strict;
< use Config;
---
> 
6a6,7
>     no strict 'vars';
>     require Config; Config->import;
```
Would that be acceptable?  And if not, why not?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
To be fair, if I were to take the most recent approach in the future Perl, then I would have to do something comparable in perl-5.32.0/blead.  In that case, the test file would start out:
```
$ head -n 14 ext/File-Glob/t/basic.t 
#!./perl
use strict;
BEGIN {
    chdir 't' if -d 't';
    @INC = '../lib';
    no strict 'vars';
    require Config; Config->import;
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
        print "1..0\n";
        exit 0;
    }
}
use Test::More tests => 49;
BEGIN {use_ok('File::Glob', ':glob')};
```
The diff between blead and the above would be:
```
$ git diff -w blead..HEAD -- ext/File-Glob/t/basic.t
diff --git a/ext/File-Glob/t/basic.t b/ext/File-Glob/t/basic.t
index d23ec7499b..4e73f44d4a 100644
--- a/ext/File-Glob/t/basic.t
+++ b/ext/File-Glob/t/basic.t
@@ -1,15 +1,15 @@
 #!./perl
-
+use strict;
 BEGIN {
     chdir 't' if -d 't';
     @INC = '../lib';
-    require Config; import Config;
+    no strict 'vars';
+    require Config; Config->import;
     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
         print "1..0\n";
         exit 0;
     }
 }
-use strict;
 use Test::More tests => 49;
 BEGIN {use_ok('File::Glob', ':glob')};
 use Cwd ();
```
And the diff between "perl-5.32+strict-at-the-beginning" and "future-perl-with-strict-by-default" would once again come down to this:
```
$ diff ext/File-Glob/t/basic.t ../perl-atoomic/ext/File-Glob/t/basic.t
2c2
< use strict;
---
> 
```
So now I believe the correct approach in future Perl would be that shown at (the top of my previous comment)[https://github.com/atoomic/perl/issues/84#issuecomment-656938142]:
* No need for 'use strict' right after the shebang line; we're in a strict-by-default world.
* Within the `BEGIN` block, we still want to precisely specify where we are to find `Config.pm`.
* Within the `BEGIN` block, we switch where needed to `use strict'vars';` and then `require Config; Config->import;` as we have traditionally done.
* The test file runs to completion and passes.

Comments?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> How about this (for future Perl/`core-p7`) instead?
> 
> ```
> $ head -n 14 ext/File-Glob/t/basic.t
> #!./perl
> 
> BEGIN {
>     chdir 't' if -d 't';
>     @INC = '../lib';
>     no strict 'vars';
>     require Config; Config->import;
>     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
>         print "1..0\n";
>         exit 0;
>     }
> }
> use Test::More tests => 49;
> BEGIN {use_ok('File::Glob', ':glob')};
> ```

If this approach is valid, then it will also work in this p.r. for **20** tests in `dist/Data-Dumper/`:
https://github.com/atoomic/perl/pull/86

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
The `no strict 'vars'` seems fine for that particular case.
I know there are other samples where `%Config` is used later after the `BEGIN` block and this would not work.
I think the cleaner solution is to split the `@INC` setup than the module load/import itself

the generic pattern should be something like this
```perl
BEGIN { # setup inc	
	unshift @INC, '.';
	# or @INC = ...
	# or set_up_inc(...)
}

# then load/use the module in a BEGIN block or not lol 
use Config;
```

in this case this could looks like

```perl
BEGIN {
    chdir 't' if -d 't';
    @INC = '../lib';
}

use Config; # can be inside the BEGIN just after or not...

BEGIN {
    if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
        print "1..0\n";
        exit 0;
    }
}
```

**Comment by jkeenan** [comment]
> The `no strict 'vars'` seems fine for that particular case.
> I know there are other samples where `%Config` is used later after the `BEGIN` block and this would not work.
> I think the cleaner solution is to split the `@INC` setup than the module load/import itself
> 
> the generic pattern should be something like this
> 
> ```perl
> BEGIN { # setup inc	
> 	unshift @INC, '.';
> 	# or @INC = ...
> 	# or set_up_inc(...)
> }
> 
> # then load/use the module in a BEGIN block or not lol 
> use Config;
> ```
> 
> in this case this could looks like
> 
> ```perl
> BEGIN {
>     chdir 't' if -d 't';
>     @INC = '../lib';
> }
> 
> use Config; # can be inside the BEGIN just after or not...
> 
> BEGIN {
>     if ($Config{'extensions'} !~ /\bFile\/Glob\b/i) {
>         print "1..0\n";
>         exit 0;
>     }
> }
> ```

I'll keep those suggestions in mind going forward (and so we'll leave this ticket open).  But I've now used the pattern I described in several dozen files, all successfully.  Since we have much to do I'm not going to revisit them now.

Later, if we want, we can create a ticket for someone (else) to examine all instances of `require Config` throughout the codebase.

**Comment by jkeenan** [comment]
We had all tests passing when we merged the branch for Objective 1 into `alpha`, so this ticket is superseded.
